// dataManager.js — Xeibo Mock State Management Utilities

const STORAGE_KEY = 'weibo_mock_state';

export function createInitialData() {
  const now = new Date('2026-04-10T12:00:00Z');
  const hoursAgo = (h) => new Date(now - h * 3600 * 1000).toISOString();
  const daysAgo = (d) => new Date(now - d * 24 * 3600 * 1000).toISOString();

  const users = {
    user_current: {
      id: 'user_current',
      screenName: '李小明',
      handle: 'lixiaoming',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=lixiaoming',
      coverImage: '',
      bio: '热爱生活，热爱分享 | 北漂青年 | 美食/旅行/科技爱好者',
      location: '北京',
      verified: false,
      verifiedType: 'none',
      followingCount: 6,
      followersCount: 512,
      postsCount: 47,
      isFollowing: false,
      createdAt: '2019-06-01T00:00:00Z',
    },
    user_1: {
      id: 'user_1',
      screenName: '央视新闻',
      handle: 'cctvnews',
      avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=央视&backgroundColor=e63946',
      coverImage: '',
      bio: '中央广播电视总台新闻中心官方微博，传播权威资讯，记录时代变迁。',
      location: '北京',
      verified: true,
      verifiedType: 'blue_v',
      followingCount: 328,
      followersCount: 15200000,
      postsCount: 45230,
      isFollowing: true,
      createdAt: '2010-03-15T00:00:00Z',
    },
    user_2: {
      id: 'user_2',
      screenName: '张伟Tech',
      handle: 'zhangweitech',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=zhangweitech',
      coverImage: '',
      bio: '科技博主 | AI/大模型深度测评 | 前BAT工程师 | 每周更新科技干货',
      location: '上海',
      verified: true,
      verifiedType: 'orange_v',
      followingCount: 892,
      followersCount: 2340000,
      postsCount: 3821,
      isFollowing: true,
      createdAt: '2012-08-20T00:00:00Z',
    },
    user_3: {
      id: 'user_3',
      screenName: '美食小厨娘',
      handle: 'meishixiaochu',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=meishixiaochu',
      coverImage: '',
      bio: '🍜 每天分享简单好吃的家常菜 | 烘焙爱好者 | 减脂餐专家 | 粉丝福利每周五',
      location: '成都',
      verified: true,
      verifiedType: 'orange_v',
      followingCount: 234,
      followersCount: 1870000,
      postsCount: 2156,
      isFollowing: true,
      createdAt: '2014-05-10T00:00:00Z',
    },
    user_4: {
      id: 'user_4',
      screenName: '华为官方微博',
      handle: 'huaweiofficial',
      avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=华为&backgroundColor=cf2e2e',
      coverImage: '',
      bio: '华为官方微博，分享最新产品资讯和技术动态。Built with Huawei.',
      location: '深圳',
      verified: true,
      verifiedType: 'gold_v',
      followingCount: 156,
      followersCount: 8900000,
      postsCount: 12450,
      isFollowing: true,
      createdAt: '2011-01-01T00:00:00Z',
    },
    user_5: {
      id: 'user_5',
      screenName: '旅行的陈默',
      handle: 'travelerchen',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=travelerchen',
      coverImage: '',
      bio: '走过60+个国家 | 背包客 | 用镜头记录世界的美好 | 旅游攻略博主',
      location: '云南',
      verified: true,
      verifiedType: 'blue_v',
      followingCount: 567,
      followersCount: 920000,
      postsCount: 1834,
      isFollowing: true,
      createdAt: '2013-09-15T00:00:00Z',
    },
    user_6: {
      id: 'user_6',
      screenName: '林晓雨',
      handle: 'linxiaoyu',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=linxiaoyu',
      coverImage: '',
      bio: '普通的上班族，喜欢追剧和看展 | 北京',
      location: '北京',
      verified: false,
      verifiedType: 'none',
      followingCount: 234,
      followersCount: 1230,
      postsCount: 186,
      isFollowing: true,
      createdAt: '2017-03-22T00:00:00Z',
    },
    user_7: {
      id: 'user_7',
      screenName: '王子豪体育',
      handle: 'wangzihao_sports',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=wangzihao',
      coverImage: '',
      bio: '体育解说员 | NBA/CBA全程跟踪 | 足球欧冠专题 | 微博体育认证',
      location: '广州',
      verified: true,
      verifiedType: 'blue_v',
      followingCount: 445,
      followersCount: 3200000,
      postsCount: 8967,
      isFollowing: false,
      createdAt: '2011-07-04T00:00:00Z',
    },
    user_8: {
      id: 'user_8',
      screenName: '周音乐人',
      handle: 'zhoumusician',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=zhoumusician',
      coverImage: '',
      bio: '独立音乐人 🎵 | 吉他/钢琴 | 已发布3张专辑 | 演出信息关注微博',
      location: '北京',
      verified: true,
      verifiedType: 'orange_v',
      followingCount: 678,
      followersCount: 450000,
      postsCount: 1023,
      isFollowing: false,
      createdAt: '2015-11-30T00:00:00Z',
    },
    user_9: {
      id: 'user_9',
      screenName: '赵小花',
      handle: 'zhaoxiaohua',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=zhaoxiaohua',
      coverImage: '',
      bio: '学生党，爱看书爱打游戏',
      location: '武汉',
      verified: false,
      verifiedType: 'none',
      followingCount: 89,
      followersCount: 456,
      postsCount: 78,
      isFollowing: false,
      createdAt: '2020-09-01T00:00:00Z',
    },
    user_10: {
      id: 'user_10',
      screenName: '刘大厨',
      handle: 'liudachu',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=liudachu',
      coverImage: '',
      bio: '厨师长，二十年厨艺经验，教你做地道中华美食',
      location: '西安',
      verified: false,
      verifiedType: 'none',
      followingCount: 123,
      followersCount: 28900,
      postsCount: 342,
      isFollowing: false,
      createdAt: '2016-02-14T00:00:00Z',
    },
    user_11: {
      id: 'user_11',
      screenName: '科技前沿报道',
      handle: 'techfrontier',
      avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=科技&backgroundColor=2d6a4f',
      coverImage: '',
      bio: '聚焦AI、芯片、5G等前沿科技领域，深度报道+独家解析',
      location: '北京',
      verified: true,
      verifiedType: 'blue_v',
      followingCount: 890,
      followersCount: 5600000,
      postsCount: 23450,
      isFollowing: false,
      createdAt: '2010-12-01T00:00:00Z',
    },
  };

  const posts = {
    post_1: {
      id: 'post_1',
      userId: 'user_1',
      text: '【最新消息】国家发展改革委今日召开新闻发布会，宣布将加大对新能源汽车产业的支持力度，包括延长购置补贴政策至2027年底，并加快充电基础设施建设。相关负责人表示，目前全国充电桩数量已突破1000万个，覆盖所有县级以上城市。#新能源汽车政策# #绿色出行#',
      images: [],
      video: null,
      createdAt: hoursAgo(2),
      source: '微博网页版',
      repostCount: 1256,
      commentCount: 892,
      likeCount: 8934,
      isLiked: false,
      isReposted: false,
      repostOf: null,
      repostText: '',
      isLongText: true,
      topicIds: ['topic_1', 'topic_2'],
    },
    post_2: {
      id: 'post_2',
      userId: 'user_2',
      text: '刚刚测试了最新发布的国产大模型，几个关键指标表现相当惊艳！代码生成能力已经超越GPT-4，推理题正确率达到92%。#AI大模型# #国产AI崛起#\n附上详细评测报告👇',
      images: [
        'https://picsum.photos/600/400?random=201',
        'https://picsum.photos/600/400?random=202',
        'https://picsum.photos/600/400?random=203',
      ],
      video: null,
      createdAt: hoursAgo(3),
      source: '微博网页版',
      repostCount: 567,
      commentCount: 234,
      likeCount: 4521,
      isLiked: true,
      isReposted: false,
      repostOf: null,
      repostText: '',
      isLongText: false,
      topicIds: ['topic_3'],
    },
    post_3: {
      id: 'post_3',
      userId: 'user_3',
      text: '今天做了一道超级简单又好吃的番茄炒蛋！只需要5个步骤就搞定，附上详细教程。关键技巧：鸡蛋要先炒熟盛出，番茄炒软出汁后再放入鸡蛋，最后加盐和白糖调味，出锅前撒葱花。强烈推荐！🍅🥚 #家常菜# #番茄炒蛋#',
      images: [
        'https://picsum.photos/500/400?random=301',
        'https://picsum.photos/500/400?random=302',
        'https://picsum.photos/500/400?random=303',
        'https://picsum.photos/500/400?random=304',
      ],
      video: null,
      createdAt: hoursAgo(5),
      source: '微博App',
      repostCount: 892,
      commentCount: 445,
      likeCount: 12340,
      isLiked: false,
      isReposted: false,
      repostOf: null,
      repostText: '',
      isLongText: false,
      topicIds: ['topic_4', 'topic_5'],
    },
    post_4: {
      id: 'post_4',
      userId: 'user_4',
      text: '华为Mate X5折叠屏新颜色「云墨青」今日正式开售！这款限定色灵感来源于中国传统水墨画，展现东方美学与现代科技的完美融合。#华为Mate# #折叠屏#',
      images: [
        'https://picsum.photos/600/500?random=401',
      ],
      video: null,
      createdAt: hoursAgo(6),
      source: '华为官方',
      repostCount: 2341,
      commentCount: 1023,
      likeCount: 23400,
      isLiked: false,
      isReposted: false,
      repostOf: null,
      repostText: '',
      isLongText: false,
      topicIds: ['topic_6'],
    },
    post_5: {
      id: 'post_5',
      userId: 'user_5',
      text: '云南大理环洱海骑行，今天路过才溪村，这里的油菜花还没有谢，漫山遍野金黄一片，美得像画一样🌻 骑行打卡第7天，腿虽然酸但是心情超好！#洱海骑行# #云南旅行#',
      images: [
        'https://picsum.photos/600/450?random=501',
        'https://picsum.photos/600/450?random=502',
        'https://picsum.photos/600/450?random=503',
        'https://picsum.photos/600/450?random=504',
        'https://picsum.photos/600/450?random=505',
        'https://picsum.photos/600/450?random=506',
        'https://picsum.photos/600/450?random=507',
        'https://picsum.photos/600/450?random=508',
        'https://picsum.photos/600/450?random=509',
      ],
      video: null,
      createdAt: hoursAgo(8),
      source: '微博App',
      repostCount: 445,
      commentCount: 289,
      likeCount: 8760,
      isLiked: true,
      isReposted: false,
      repostOf: null,
      repostText: '',
      isLongText: false,
      topicIds: ['topic_7', 'topic_8'],
    },
    post_6: {
      id: 'post_6',
      userId: 'user_2',
      text: '转发并评论 @张伟Tech 的这条微博，真的太有见地了！',
      images: [],
      video: null,
      createdAt: hoursAgo(10),
      source: '微博网页版',
      repostCount: 89,
      commentCount: 34,
      likeCount: 567,
      isLiked: false,
      isReposted: false,
      repostOf: 'post_1',
      repostText: '这个政策对新能源行业是重大利好，充电桩的快速普及是电动车大规模推广的关键！',
      isLongText: false,
      topicIds: [],
    },
    post_7: {
      id: 'post_7',
      userId: 'user_6',
      text: '今天看了《繁花》第二遍，果然越看越有味道。王家卫用光影和旁白构建了一个既真实又梦幻的90年代上海，每一帧都像一幅画。胡歌演的宝总太绝了，不着痕迹的克制感。推荐还没看的朋友去补，值得！',
      images: [],
      video: null,
      createdAt: hoursAgo(12),
      source: '微博App',
      repostCount: 23,
      commentCount: 45,
      likeCount: 234,
      isLiked: false,
      isReposted: false,
      repostOf: null,
      repostText: '',
      isLongText: false,
      topicIds: ['topic_9'],
    },
    post_8: {
      id: 'post_8',
      userId: 'user_7',
      text: '【深度分析】今晚CBA总决赛G3，辽宁男篮主场迎战广东宏远。从技战术角度分析：辽宁外线三分命中率在系列赛中高达45%，是本场胜负的关键。广东需要加强对林书豪的防守强度，限制其突破分球。预测：辽宁主场优势明显，有望2-1取得系列赛领先。#CBA总决赛# #辽宁男篮#',
      images: [
        'https://picsum.photos/700/400?random=801',
        'https://picsum.photos/700/400?random=802',
      ],
      video: null,
      createdAt: hoursAgo(14),
      source: '微博网页版',
      repostCount: 678,
      commentCount: 445,
      likeCount: 5670,
      isLiked: false,
      isReposted: false,
      repostOf: null,
      repostText: '',
      isLongText: true,
      topicIds: ['topic_10'],
    },
    post_9: {
      id: 'post_9',
      userId: 'user_8',
      text: '新专辑《城市之声》正式发布！历经两年创作，12首原创曲目，记录了我在北京这座城市的喜怒哀乐。感谢每一位陪伴我走到今天的朋友和粉丝，爱你们🎵 专辑已上线各大音乐平台，欢迎收听！',
      images: [
        'https://picsum.photos/500/500?random=901',
      ],
      video: null,
      createdAt: hoursAgo(18),
      source: '微博App',
      repostCount: 1230,
      commentCount: 890,
      likeCount: 45600,
      isLiked: true,
      isReposted: false,
      repostOf: null,
      repostText: '',
      isLongText: false,
      topicIds: [],
    },
    post_10: {
      id: 'post_10',
      userId: 'user_current',
      text: '今天在三里屯发现了一家超棒的咖啡店，环境特别好，咖啡的口感也很不错！强烈推荐拿铁，奶泡打得很细腻。下次有机会要带朋友再来 ☕ @林晓雨 上次你说要找好吃的咖啡，这家可以试试！',
      images: [
        'https://picsum.photos/500/400?random=1001',
        'https://picsum.photos/500/400?random=1002',
      ],
      video: null,
      createdAt: hoursAgo(20),
      source: '微博网页版',
      repostCount: 12,
      commentCount: 8,
      likeCount: 56,
      isLiked: false,
      isReposted: false,
      repostOf: null,
      repostText: '',
      isLongText: false,
      topicIds: [],
    },
    post_11: {
      id: 'post_11',
      userId: 'user_11',
      text: '【重磅】OpenAI宣布GPT-5正式发布，多模态能力大幅提升！根据官方测试数据，在数学推理、代码生成、医学诊断等多个专业领域均超越人类专家水平。国内各大AI公司纷纷表示将加快研发步伐迎接竞争。这场AI军备竞赛，中国准备好了吗？ #GPT5# #AI发展#',
      images: [],
      video: null,
      createdAt: hoursAgo(24),
      source: '微博网页版',
      repostCount: 3456,
      commentCount: 2341,
      likeCount: 34500,
      isLiked: false,
      isReposted: false,
      repostOf: null,
      repostText: '',
      isLongText: true,
      topicIds: ['topic_3'],
    },
    post_12: {
      id: 'post_12',
      userId: 'user_3',
      text: '春天来了，做了一锅清淡的春笋腊肉饭，食材都是当季的，清香四溢。今年春笋特别嫩，做法简单：笋切片焯水去涩，腊肉煸出油脂，加入笋片翻炒，最后加米饭拌匀即可。附上步骤图🌱 #春季养生# #笋的做法#',
      images: [
        'https://picsum.photos/480/360?random=1201',
        'https://picsum.photos/480/360?random=1202',
        'https://picsum.photos/480/360?random=1203',
        'https://picsum.photos/480/360?random=1204',
        'https://picsum.photos/480/360?random=1205',
        'https://picsum.photos/480/360?random=1206',
      ],
      video: null,
      createdAt: hoursAgo(28),
      source: '微博App',
      repostCount: 567,
      commentCount: 234,
      likeCount: 7890,
      isLiked: false,
      isReposted: false,
      repostOf: null,
      repostText: '',
      isLongText: false,
      topicIds: ['topic_5'],
    },
    post_13: {
      id: 'post_13',
      userId: 'user_5',
      text: '大理苍山雪，洱海月，今晚有幸拍到了难得一见的苍山雪景倒映在洱海中的景色。零下4度，站在湖边冻得瑟瑟发抖，但这一幕真的值得！旅行就是要不断发现这样的惊喜🏔️❄️',
      images: [
        'https://picsum.photos/700/500?random=1301',
      ],
      video: null,
      createdAt: hoursAgo(36),
      source: '微博App',
      repostCount: 234,
      commentCount: 123,
      likeCount: 3450,
      isLiked: false,
      isReposted: false,
      repostOf: null,
      repostText: '',
      isLongText: false,
      topicIds: ['topic_8'],
    },
    post_14: {
      id: 'post_14',
      userId: 'user_9',
      text: '考研完了！！！！三年的努力终于结束了，不管结果怎样，这段拼命备考的时光是我这辈子最珍贵的经历之一。感谢一路陪伴的小伙伴们，感谢图书馆，感谢泡面🙏',
      images: [],
      video: null,
      createdAt: hoursAgo(40),
      source: '微博App',
      repostCount: 56,
      commentCount: 89,
      likeCount: 1234,
      isLiked: true,
      isReposted: false,
      repostOf: null,
      repostText: '',
      isLongText: false,
      topicIds: [],
    },
    post_15: {
      id: 'post_15',
      userId: 'user_1',
      text: '【航天快讯】中国空间站今日迎来新一批航天员，神舟十九号乘组圆满完成了为期约6个月的太空飞行任务，安全返回地球。三名航天员状态良好，已在酒泉卫星发射中心完成医学检查。#神舟十九号# #中国航天#',
      images: [
        'https://picsum.photos/800/450?random=1501',
        'https://picsum.photos/800/450?random=1502',
      ],
      video: null,
      createdAt: hoursAgo(48),
      source: '微博网页版',
      repostCount: 4567,
      commentCount: 2345,
      likeCount: 67800,
      isLiked: false,
      isReposted: false,
      repostOf: null,
      repostText: '',
      isLongText: false,
      topicIds: [],
    },
    post_16: {
      id: 'post_16',
      userId: 'user_4',
      text: '鸿蒙HarmonyOS NEXT 4.0正式发布！全面去安卓化，完全基于自研内核，应用生态已突破15万个。小艺助手接入最新大模型，语音交互体验大幅提升。欢迎大家升级体验！#鸿蒙系统# #华为#',
      images: [
        'https://picsum.photos/700/400?random=1601',
        'https://picsum.photos/700/400?random=1602',
        'https://picsum.photos/700/400?random=1603',
        'https://picsum.photos/700/400?random=1604',
      ],
      video: null,
      createdAt: daysAgo(2),
      source: '华为官方',
      repostCount: 5678,
      commentCount: 3456,
      likeCount: 89000,
      isLiked: false,
      isReposted: false,
      repostOf: null,
      repostText: '',
      isLongText: false,
      topicIds: ['topic_6'],
    },
    post_17: {
      id: 'post_17',
      userId: 'user_6',
      text: '在博物馆看到了这件汉代玉衣，真的震撼到了。两千多年前的工匠用金线将2498块玉片连缀在一起，精密程度令人叹为观止。中华文明的厚度，每次来博物馆都有新的感触。',
      images: [
        'https://picsum.photos/500/600?random=1701',
        'https://picsum.photos/500/600?random=1702',
      ],
      video: null,
      createdAt: daysAgo(2),
      source: '微博App',
      repostCount: 167,
      commentCount: 89,
      likeCount: 2340,
      isLiked: false,
      isReposted: false,
      repostOf: null,
      repostText: '',
      isLongText: false,
      topicIds: [],
    },
    post_18: {
      id: 'post_18',
      userId: 'user_10',
      text: '陕西人不能接受的几种关中面做法：1.放酱油的臊子面；2.加番茄的油泼面；3.不放辣子的裤带面。我们这里有句话"油泼辣子一道菜"，没有辣子的面那叫什么面！今天给大家示范正宗的陕西油泼面做法👇',
      images: [
        'https://picsum.photos/600/400?random=1801',
        'https://picsum.photos/600/400?random=1802',
        'https://picsum.photos/600/400?random=1803',
      ],
      video: null,
      createdAt: daysAgo(2),
      source: '微博App',
      repostCount: 234,
      commentCount: 178,
      likeCount: 4560,
      isLiked: true,
      isReposted: false,
      repostOf: null,
      repostText: '',
      isLongText: false,
      topicIds: ['topic_5'],
    },
    post_19: {
      id: 'post_19',
      userId: 'user_9',
      text: '转发了 @华为官方微博 的鸿蒙系统新版本发布！',
      images: [],
      video: null,
      createdAt: daysAgo(2),
      source: '微博App',
      repostCount: 3,
      commentCount: 1,
      likeCount: 12,
      isLiked: false,
      isReposted: false,
      repostOf: 'post_16',
      repostText: '终于等到全面去安卓化的鸿蒙系统了！国产软件加油！',
      isLongText: false,
      topicIds: [],
    },
    post_20: {
      id: 'post_20',
      userId: 'user_2',
      text: '最近深度体验了几款国产大模型的代码生成能力，做了一个横向对比测评。测试了Python、JavaScript、Java三种语言，各选10道算法题和5道工程题。总体结论：国产大模型在中文编程任务上已经追平甚至超越GPT-4，但英文文档生成和国际化开发场景仍有差距。详细报告见评论区。 #AI测评# #大模型比较#',
      images: [
        'https://picsum.photos/700/500?random=2001',
      ],
      video: null,
      createdAt: daysAgo(3),
      source: '微博网页版',
      repostCount: 1234,
      commentCount: 567,
      likeCount: 12300,
      isLiked: false,
      isReposted: false,
      repostOf: null,
      repostText: '',
      isLongText: true,
      topicIds: ['topic_3'],
    },
    post_21: {
      id: 'post_21',
      userId: 'user_7',
      text: '今晚NBA西部半决赛：湖人vs掘金，詹姆斯42岁仍然能拿到30+的数据，真的是历史第一人。约基奇三双依旧稳定。这场比赛第四节最后两分钟的攻防转换太精彩了！#NBA季后赛# #詹姆斯#',
      images: [
        'https://picsum.photos/700/400?random=2101',
        'https://picsum.photos/700/400?random=2102',
      ],
      video: null,
      createdAt: daysAgo(3),
      source: '微博网页版',
      repostCount: 890,
      commentCount: 567,
      likeCount: 8900,
      isLiked: false,
      isReposted: false,
      repostOf: null,
      repostText: '',
      isLongText: false,
      topicIds: [],
    },
    post_22: {
      id: 'post_22',
      userId: 'user_current',
      text: '分享一本最近读完的书《人类简史》，虽然是老书了但每次重读都有新的感悟。作者从认知革命、农业革命和科学革命三个维度重新审视人类文明的发展历程，读完有种豁然开朗的感觉。推荐给还没看过的朋友！',
      images: [],
      video: null,
      createdAt: daysAgo(4),
      source: '微博App',
      repostCount: 5,
      commentCount: 12,
      likeCount: 89,
      isLiked: false,
      isReposted: false,
      repostOf: null,
      repostText: '',
      isLongText: false,
      topicIds: [],
    },
    post_23: {
      id: 'post_23',
      userId: 'user_11',
      text: '【深度分析】苹果最新M4芯片架构详解：4nm制程工艺，16核CPU+40核GPU，AI算力翻倍。但更值得关注的是其NPU设计，专门针对端侧大模型推理进行了优化。中国芯片企业需要在AI芯片架构上加速追赶。 #苹果M4# #芯片#',
      images: [
        'https://picsum.photos/700/400?random=2301',
      ],
      video: null,
      createdAt: daysAgo(4),
      source: '微博网页版',
      repostCount: 2345,
      commentCount: 1234,
      likeCount: 23400,
      isLiked: true,
      isReposted: false,
      repostOf: null,
      repostText: '',
      isLongText: true,
      topicIds: [],
    },
    post_24: {
      id: 'post_24',
      userId: 'user_10',
      text: '今天教大家做正宗的西安肉夹馍！白吉馍要用老面发酵，腊汁肉要用猪前腿肉慢炖4小时。关键是香料配方：八角、桂皮、花椒、草果、丁香、小茴香，比例很讲究。视频教程明天更新，先看看成品图！#陕西美食# #肉夹馍#',
      images: [
        'https://picsum.photos/500/400?random=2401',
        'https://picsum.photos/500/400?random=2402',
        'https://picsum.photos/500/400?random=2403',
        'https://picsum.photos/500/400?random=2404',
      ],
      video: null,
      createdAt: daysAgo(4),
      source: '微博App',
      repostCount: 456,
      commentCount: 234,
      likeCount: 6780,
      isLiked: false,
      isReposted: false,
      repostOf: null,
      repostText: '',
      isLongText: false,
      topicIds: ['topic_5'],
    },
    post_25: {
      id: 'post_25',
      userId: 'user_8',
      text: '今晚在北京MAO livehouse的演出圆满结束！感谢到场的每一位朋友，你们的热情让我感动到哭了。新歌《深夜地铁》的首唱反响超出预期，很多人在台下跟着合唱副歌部分。下一站上海，5月3日见！',
      images: [
        'https://picsum.photos/600/400?random=2501',
        'https://picsum.photos/600/400?random=2502',
        'https://picsum.photos/600/400?random=2503',
      ],
      video: null,
      createdAt: daysAgo(5),
      source: '微博App',
      repostCount: 789,
      commentCount: 456,
      likeCount: 23400,
      isLiked: false,
      isReposted: false,
      repostOf: null,
      repostText: '',
      isLongText: false,
      topicIds: [],
    },
    post_26: {
      id: 'post_26',
      userId: 'user_5',
      text: '结束了大理之旅，飞往下一站——丽江。这次环洱海骑行10天的总结：总里程320公里，拍了2000+张照片，结识了8位来自不同城市的骑友，吃了不下30碗过桥米线。旅行的意义不在于目的地，而在于沿途遇见的人和风景。#旅行的意义#',
      images: [
        'https://picsum.photos/600/400?random=2601',
        'https://picsum.photos/600/400?random=2602',
        'https://picsum.photos/600/400?random=2603',
        'https://picsum.photos/600/400?random=2604',
        'https://picsum.photos/600/400?random=2605',
        'https://picsum.photos/600/400?random=2606',
        'https://picsum.photos/600/400?random=2607',
        'https://picsum.photos/600/400?random=2608',
        'https://picsum.photos/600/400?random=2609',
      ],
      video: null,
      createdAt: daysAgo(5),
      source: '微博App',
      repostCount: 567,
      commentCount: 345,
      likeCount: 12300,
      isLiked: false,
      isReposted: false,
      repostOf: null,
      repostText: '',
      isLongText: false,
      topicIds: ['topic_8'],
    },
    post_27: {
      id: 'post_27',
      userId: 'user_1',
      text: '【突发】教育部今日发布通知：2026年秋季学期起，全国中小学将全面推广人工智能基础课程，覆盖三至九年级。课程内容包括AI基本原理、编程思维训练和数据素养培养。这标志着AI教育正式纳入国家基础教育体系。#AI教育# #教育改革#',
      images: [],
      video: null,
      createdAt: daysAgo(6),
      source: '微博网页版',
      repostCount: 5670,
      commentCount: 3456,
      likeCount: 45600,
      isLiked: false,
      isReposted: false,
      repostOf: null,
      repostText: '',
      isLongText: true,
      topicIds: [],
    },
  };

  const comments = {
    comment_1: {
      id: 'comment_1',
      postId: 'post_1',
      userId: 'user_2',
      text: '充电桩1000万个这个数据很厉害！不过希望能解决农村地区和高速公路充电难的问题，这才是真正的痛点。',
      createdAt: hoursAgo(1.5),
      likeCount: 234,
      isLiked: false,
      replyToId: null,
      replyToUserId: null,
    },
    comment_2: {
      id: 'comment_2',
      postId: 'post_1',
      userId: 'user_5',
      text: '回复 @张伟Tech：同意！我骑行途中遇到最大的问题就是偏远地区充电难，希望这次政策能覆盖到县乡级别。',
      createdAt: hoursAgo(1.2),
      likeCount: 89,
      isLiked: true,
      replyToId: 'comment_1',
      replyToUserId: 'user_2',
    },
    comment_3: {
      id: 'comment_3',
      postId: 'post_1',
      userId: 'user_6',
      text: '政策很好！期待落实到位，不要变成数字游戏。',
      createdAt: hoursAgo(1.1),
      likeCount: 167,
      isLiked: false,
      replyToId: null,
      replyToUserId: null,
    },
    comment_4: {
      id: 'comment_4',
      postId: 'post_1',
      userId: 'user_9',
      text: '终于！这个政策早就该出了，很多朋友因为充电不方便不敢买电动车。',
      createdAt: hoursAgo(1),
      likeCount: 123,
      isLiked: false,
      replyToId: null,
      replyToUserId: null,
    },
    comment_5: {
      id: 'comment_5',
      postId: 'post_1',
      userId: 'user_10',
      text: '作为一个每天开车的人，真的希望能尽快实现家门口10公里内就有快充桩。',
      createdAt: hoursAgo(0.8),
      likeCount: 78,
      isLiked: false,
      replyToId: null,
      replyToUserId: null,
    },
    comment_6: {
      id: 'comment_6',
      postId: 'post_1',
      userId: 'user_7',
      text: '这个数据准确吗？1000万个充电桩，但很多是家用慢充，公共快充比例才是关键。',
      createdAt: hoursAgo(0.5),
      likeCount: 345,
      isLiked: true,
      replyToId: null,
      replyToUserId: null,
    },
    comment_7: {
      id: 'comment_7',
      postId: 'post_1',
      userId: 'user_2',
      text: '回复 @王子豪体育：有道理！公共快充和家用慢充的比例大约是3:7，公共快充覆盖率确实需要提升。',
      createdAt: hoursAgo(0.3),
      likeCount: 112,
      isLiked: false,
      replyToId: 'comment_6',
      replyToUserId: 'user_7',
    },
    comment_8: {
      id: 'comment_8',
      postId: 'post_1',
      userId: 'user_current',
      text: '这条新闻很及时，我正在考虑要不要换电动车，政策这么好应该入手了！',
      createdAt: hoursAgo(0.1),
      likeCount: 34,
      isLiked: false,
      replyToId: null,
      replyToUserId: null,
    },
    comment_9: {
      id: 'comment_9',
      postId: 'post_2',
      userId: 'user_11',
      text: '测试结果很有价值！能分享一下测试的具体题目吗？想用同样的题目自己对比测试一下。',
      createdAt: hoursAgo(2.5),
      likeCount: 67,
      isLiked: false,
      replyToId: null,
      replyToUserId: null,
    },
    comment_10: {
      id: 'comment_10',
      postId: 'post_2',
      userId: 'user_current',
      text: '国产大模型加油！希望能尽快超越GPT-5！',
      createdAt: hoursAgo(2.2),
      likeCount: 45,
      isLiked: false,
      replyToId: null,
      replyToUserId: null,
    },
    comment_11: {
      id: 'comment_11',
      postId: 'post_2',
      userId: 'user_9',
      text: '大佬能推荐一下哪个国产大模型最好用吗？准备用来辅助写论文。',
      createdAt: hoursAgo(2),
      likeCount: 89,
      isLiked: true,
      replyToId: null,
      replyToUserId: null,
    },
    comment_12: {
      id: 'comment_12',
      postId: 'post_2',
      userId: 'user_2',
      text: '回复 @赵小花：写论文推荐文心一言和通义千问，中文理解和生成能力很强，而且对学术写作有专门优化。',
      createdAt: hoursAgo(1.8),
      likeCount: 156,
      isLiked: false,
      replyToId: 'comment_11',
      replyToUserId: 'user_9',
    },
    comment_13: {
      id: 'comment_13',
      postId: 'post_2',
      userId: 'user_6',
      text: '感谢博主！这篇评测比那些付费咨询报告更有干货。',
      createdAt: hoursAgo(1.5),
      likeCount: 78,
      isLiked: false,
      replyToId: null,
      replyToUserId: null,
    },
    comment_14: {
      id: 'comment_14',
      postId: 'post_3',
      userId: 'user_current',
      text: '番茄炒蛋是我最爱的家常菜！下次试试你这个配方，看看是不是比我妈做的更好吃😂',
      createdAt: hoursAgo(4.5),
      likeCount: 234,
      isLiked: false,
      replyToId: null,
      replyToUserId: null,
    },
    comment_15: {
      id: 'comment_15',
      postId: 'post_3',
      userId: 'user_10',
      text: '专业点评：鸡蛋要用中小火慢炒，避免过老。番茄出汁后加少许鸡精增鲜，效果更好。',
      createdAt: hoursAgo(4.2),
      likeCount: 345,
      isLiked: true,
      replyToId: null,
      replyToUserId: null,
    },
    comment_16: {
      id: 'comment_16',
      postId: 'post_3',
      userId: 'user_9',
      text: '学会了！今晚就做！',
      createdAt: hoursAgo(4),
      likeCount: 56,
      isLiked: false,
      replyToId: null,
      replyToUserId: null,
    },
    comment_17: {
      id: 'comment_17',
      postId: 'post_3',
      userId: 'user_6',
      text: '我们家喜欢加一点老醋，提鲜效果很好，推荐试试！',
      createdAt: hoursAgo(3.8),
      likeCount: 89,
      isLiked: false,
      replyToId: null,
      replyToUserId: null,
    },
    comment_18: {
      id: 'comment_18',
      postId: 'post_5',
      userId: 'user_6',
      text: '洱海真的好美！去年春天去的，可惜当时没有拍到这么好的照片。',
      createdAt: hoursAgo(7.5),
      likeCount: 67,
      isLiked: false,
      replyToId: null,
      replyToUserId: null,
    },
    comment_19: {
      id: 'comment_19',
      postId: 'post_5',
      userId: 'user_current',
      text: '太美了！计划今年五一去大理，这组照片让我更期待了！',
      createdAt: hoursAgo(7),
      likeCount: 45,
      isLiked: false,
      replyToId: null,
      replyToUserId: null,
    },
    comment_20: {
      id: 'comment_20',
      postId: 'post_5',
      userId: 'user_9',
      text: '骑行第7天了！腿不酸吗哈哈哈，佩服佩服！',
      createdAt: hoursAgo(6.8),
      likeCount: 112,
      isLiked: true,
      replyToId: null,
      replyToUserId: null,
    },
    comment_21: {
      id: 'comment_21',
      postId: 'post_8',
      userId: 'user_current',
      text: '辽宁今晚必赢！在场馆现场看球，气氛超燃！',
      createdAt: hoursAgo(13),
      likeCount: 234,
      isLiked: false,
      replyToId: null,
      replyToUserId: null,
    },
    comment_22: {
      id: 'comment_22',
      postId: 'post_8',
      userId: 'user_9',
      text: '广东粉丝表示不服！今晚我们要赢！',
      createdAt: hoursAgo(12.8),
      likeCount: 189,
      isLiked: false,
      replyToId: null,
      replyToUserId: null,
    },
    comment_23: {
      id: 'comment_23',
      postId: 'post_9',
      userId: 'user_current',
      text: '恭喜周老师！《夜雨寄北》那首歌太感动了，循环了一整天。',
      createdAt: hoursAgo(17),
      likeCount: 456,
      isLiked: true,
      replyToId: null,
      replyToUserId: null,
    },
    comment_24: {
      id: 'comment_24',
      postId: 'post_9',
      userId: 'user_6',
      text: '《城市之声》已经收藏了！每一首都是精品，制作水准很高。',
      createdAt: hoursAgo(16.5),
      likeCount: 234,
      isLiked: false,
      replyToId: null,
      replyToUserId: null,
    },
    comment_25: {
      id: 'comment_25',
      postId: 'post_10',
      userId: 'user_6',
      text: '我去过！那家叫"云隐"的咖啡店对吗？拿铁确实是我在北京喝过最好喝的！',
      createdAt: hoursAgo(19),
      likeCount: 34,
      isLiked: false,
      replyToId: null,
      replyToUserId: null,
    },
    comment_26: {
      id: 'comment_26',
      postId: 'post_10',
      userId: 'user_current',
      text: '回复 @林晓雨：对的就是那家！下次一起去！',
      createdAt: hoursAgo(18.5),
      likeCount: 12,
      isLiked: false,
      replyToId: 'comment_25',
      replyToUserId: 'user_6',
    },
    comment_27: {
      id: 'comment_27',
      postId: 'post_14',
      userId: 'user_current',
      text: '加油！结果一定会好的！你的努力值得最好的回报！',
      createdAt: hoursAgo(39),
      likeCount: 89,
      isLiked: false,
      replyToId: null,
      replyToUserId: null,
    },
    comment_28: {
      id: 'comment_28',
      postId: 'post_14',
      userId: 'user_6',
      text: '考完研的感觉太好了！给你加油！',
      createdAt: hoursAgo(38.5),
      likeCount: 67,
      isLiked: false,
      replyToId: null,
      replyToUserId: null,
    },
    comment_29: {
      id: 'comment_29',
      postId: 'post_18',
      userId: 'user_current',
      text: '作为四川人，默默同情你们陕西人...我们这里任何面食都会加辣椒哈哈哈',
      createdAt: daysAgo(2),
      likeCount: 234,
      isLiked: false,
      replyToId: null,
      replyToUserId: null,
    },
    comment_30: {
      id: 'comment_30',
      postId: 'post_18',
      userId: 'user_3',
      text: '同是美食爱好者，陕西的各类面食真的是一绝！下次去西安一定要去你的店里打卡！',
      createdAt: daysAgo(2),
      likeCount: 178,
      isLiked: true,
      replyToId: null,
      replyToUserId: null,
    },
    comment_31: {
      id: 'comment_31',
      postId: 'post_4',
      userId: 'user_2',
      text: '颜色很好看！这个云墨青的配色很有质感，比之前的颜色都好看。',
      createdAt: hoursAgo(5.5),
      likeCount: 123,
      isLiked: false,
      replyToId: null,
      replyToUserId: null,
    },
    comment_32: {
      id: 'comment_32',
      postId: 'post_4',
      userId: 'user_9',
      text: '折叠屏什么时候能降到5000以内啊...穷学生表示只能看看',
      createdAt: hoursAgo(5.2),
      likeCount: 234,
      isLiked: true,
      replyToId: null,
      replyToUserId: null,
    },
    comment_33: {
      id: 'comment_33',
      postId: 'post_4',
      userId: 'user_11',
      text: '从技术角度来看，铰链设计有了很大突破，折痕几乎看不到了。',
      createdAt: hoursAgo(5),
      likeCount: 89,
      isLiked: false,
      replyToId: null,
      replyToUserId: null,
    },
    comment_34: {
      id: 'comment_34',
      postId: 'post_7',
      userId: 'user_current',
      text: '繁花真的是神作！宝总的克制演技太到位了。',
      createdAt: hoursAgo(11),
      likeCount: 56,
      isLiked: false,
      replyToId: null,
      replyToUserId: null,
    },
    comment_35: {
      id: 'comment_35',
      postId: 'post_7',
      userId: 'user_9',
      text: '每一帧都能当壁纸！摄影师太牛了。',
      createdAt: hoursAgo(10.5),
      likeCount: 78,
      isLiked: false,
      replyToId: null,
      replyToUserId: null,
    },
    comment_36: {
      id: 'comment_36',
      postId: 'post_11',
      userId: 'user_2',
      text: '作为业内人士说一句：GPT-5确实很强，但国产大模型的追赶速度超出预期，差距在缩小。',
      createdAt: hoursAgo(23),
      likeCount: 567,
      isLiked: true,
      replyToId: null,
      replyToUserId: null,
    },
    comment_37: {
      id: 'comment_37',
      postId: 'post_11',
      userId: 'user_current',
      text: '国产AI加油！相信未来会有更多突破！',
      createdAt: hoursAgo(22),
      likeCount: 123,
      isLiked: false,
      replyToId: null,
      replyToUserId: null,
    },
    comment_38: {
      id: 'comment_38',
      postId: 'post_11',
      userId: 'user_7',
      text: '评论区大佬多，能不能简单解释一下GPT-5跟之前版本有什么质的飞跃？',
      createdAt: hoursAgo(21),
      likeCount: 234,
      isLiked: false,
      replyToId: null,
      replyToUserId: null,
    },
    comment_39: {
      id: 'comment_39',
      postId: 'post_11',
      userId: 'user_2',
      text: '回复 @王子豪体育：最大的突破是reasoning能力，可以进行多步逻辑推理，类似人类的"思考链"。',
      createdAt: hoursAgo(20.5),
      likeCount: 345,
      isLiked: false,
      replyToId: 'comment_38',
      replyToUserId: 'user_7',
    },
    comment_40: {
      id: 'comment_40',
      postId: 'post_15',
      userId: 'user_7',
      text: '航天事业每一步都令人自豪！期待下一次载人登月！',
      createdAt: hoursAgo(47),
      likeCount: 456,
      isLiked: false,
      replyToId: null,
      replyToUserId: null,
    },
    comment_41: {
      id: 'comment_41',
      postId: 'post_15',
      userId: 'user_current',
      text: '致敬所有航天工作者！',
      createdAt: hoursAgo(46),
      likeCount: 234,
      isLiked: true,
      replyToId: null,
      replyToUserId: null,
    },
    comment_42: {
      id: 'comment_42',
      postId: 'post_16',
      userId: 'user_2',
      text: '终于完全去安卓化了！测了一下鸿蒙原生应用启动速度确实快了不少。',
      createdAt: daysAgo(2),
      likeCount: 567,
      isLiked: false,
      replyToId: null,
      replyToUserId: null,
    },
    comment_43: {
      id: 'comment_43',
      postId: 'post_16',
      userId: 'user_11',
      text: '15万个原生应用，生态已经基本够用了。微信、支付宝、淘宝都有原生版。',
      createdAt: daysAgo(2),
      likeCount: 345,
      isLiked: true,
      replyToId: null,
      replyToUserId: null,
    },
    comment_44: {
      id: 'comment_44',
      postId: 'post_16',
      userId: 'user_6',
      text: '已经升级了！流畅度确实有提升，小艺助手也变聪明了。',
      createdAt: daysAgo(2),
      likeCount: 123,
      isLiked: false,
      replyToId: null,
      replyToUserId: null,
    },
    comment_45: {
      id: 'comment_45',
      postId: 'post_21',
      userId: 'user_current',
      text: '詹姆斯太强了！42岁还能这么打，太不可思议了！',
      createdAt: daysAgo(3),
      likeCount: 89,
      isLiked: false,
      replyToId: null,
      replyToUserId: null,
    },
    comment_46: {
      id: 'comment_46',
      postId: 'post_21',
      userId: 'user_9',
      text: '掘金的防守真的太好了，约基奇的低位进攻无解。',
      createdAt: daysAgo(3),
      likeCount: 67,
      isLiked: false,
      replyToId: null,
      replyToUserId: null,
    },
    comment_47: {
      id: 'comment_47',
      postId: 'post_24',
      userId: 'user_3',
      text: '作为美食博主表示：这个肉夹馍看起来太正宗了！流口水了！',
      createdAt: daysAgo(4),
      likeCount: 234,
      isLiked: false,
      replyToId: null,
      replyToUserId: null,
    },
    comment_48: {
      id: 'comment_48',
      postId: 'post_24',
      userId: 'user_current',
      text: '期待视频教程！最近在学做陕西面食，希望也能出个教程！',
      createdAt: daysAgo(4),
      likeCount: 56,
      isLiked: false,
      replyToId: null,
      replyToUserId: null,
    },
    comment_49: {
      id: 'comment_49',
      postId: 'post_25',
      userId: 'user_6',
      text: '我在现场！《深夜地铁》那首歌唱哭了好多人，太有共鸣了。',
      createdAt: daysAgo(5),
      likeCount: 345,
      isLiked: true,
      replyToId: null,
      replyToUserId: null,
    },
    comment_50: {
      id: 'comment_50',
      postId: 'post_25',
      userId: 'user_current',
      text: '上海场一定去！已经买好票了！',
      createdAt: daysAgo(5),
      likeCount: 89,
      isLiked: false,
      replyToId: null,
      replyToUserId: null,
    },
    comment_51: {
      id: 'comment_51',
      postId: 'post_27',
      userId: 'user_2',
      text: 'AI教育从娃娃抓起，这是非常正确的方向！',
      createdAt: daysAgo(6),
      likeCount: 678,
      isLiked: false,
      replyToId: null,
      replyToUserId: null,
    },
    comment_52: {
      id: 'comment_52',
      postId: 'post_27',
      userId: 'user_11',
      text: '作为科技记者，我认为师资力量是最大的挑战。很多地方找不到够资格教AI的老师。',
      createdAt: daysAgo(6),
      likeCount: 456,
      isLiked: true,
      replyToId: null,
      replyToUserId: null,
    },
    comment_53: {
      id: 'comment_53',
      postId: 'post_27',
      userId: 'user_9',
      text: '要是我小时候就有这个课程就好了！现在大学才开始学AI感觉起步太晚了。',
      createdAt: daysAgo(6),
      likeCount: 234,
      isLiked: false,
      replyToId: null,
      replyToUserId: null,
    },
  };

  const hotSearches = [
    { id: 'hot_1', rank: 1, title: '神舟二十号成功发射', searchCount: 8560000, category: '社会', badge: 'boil', url: '/search?q=神舟二十号成功发射' },
    { id: 'hot_2', rank: 2, title: '国产AI超越GPT4', searchCount: 6780000, category: '科技', badge: 'boil', url: '/search?q=国产AI超越GPT4' },
    { id: 'hot_3', rank: 3, title: '五一假期出行预测', searchCount: 5340000, category: '社会', badge: 'boil', url: '/search?q=五一假期出行预测' },
    { id: 'hot_4', rank: 4, title: 'CBA总决赛辽宁广东', searchCount: 4120000, category: '体育', badge: 'hot', url: '/search?q=CBA总决赛辽宁广东' },
    { id: 'hot_5', rank: 5, title: '鸿蒙系统全面去安卓化', searchCount: 3890000, category: '科技', badge: 'hot', url: '/search?q=鸿蒙系统全面去安卓化' },
    { id: 'hot_6', rank: 6, title: '春天第一杯奶茶', searchCount: 2980000, category: '生活', badge: 'new', url: '/search?q=春天第一杯奶茶' },
    { id: 'hot_7', rank: 7, title: '新能源汽车补贴延至2027', searchCount: 2760000, category: '财经', badge: 'hot', url: '/search?q=新能源汽车补贴延至2027' },
    { id: 'hot_8', rank: 8, title: '繁花第二季官宣', searchCount: 2340000, category: '娱乐', badge: 'new', url: '/search?q=繁花第二季官宣' },
    { id: 'hot_9', rank: 9, title: '大理洱海油菜花', searchCount: 1980000, category: '生活', badge: 'hot', url: '/search?q=大理洱海油菜花' },
    { id: 'hot_10', rank: 10, title: '考研成绩查询', searchCount: 1750000, category: '教育', badge: 'new', url: '/search?q=考研成绩查询' },
    { id: 'hot_11', rank: 11, title: '北京春天赏花攻略', searchCount: 1560000, category: '生活', badge: 'hot', url: '/search?q=北京春天赏花攻略' },
    { id: 'hot_12', rank: 12, title: '豆瓣评分最高国产剧', searchCount: 1340000, category: '娱乐', badge: '', url: '/search?q=豆瓣评分最高国产剧' },
    { id: 'hot_13', rank: 13, title: '2026年最值得买的手机', searchCount: 1230000, category: '科技', badge: 'hot', url: '/search?q=2026年最值得买的手机' },
    { id: 'hot_14', rank: 14, title: '上海迪士尼新游乐项目', searchCount: 1120000, category: '生活', badge: 'new', url: '/search?q=上海迪士尼新游乐项目' },
    { id: 'hot_15', rank: 15, title: '全球最大光刻机发布', searchCount: 1050000, category: '科技', badge: 'hot', url: '/search?q=全球最大光刻机发布' },
    { id: 'hot_16', rank: 16, title: '北京马拉松报名开始', searchCount: 980000, category: '体育', badge: '', url: '/search?q=北京马拉松报名开始' },
    { id: 'hot_17', rank: 17, title: '中国股市大盘走势', searchCount: 920000, category: '财经', badge: 'hot', url: '/search?q=中国股市大盘走势' },
    { id: 'hot_18', rank: 18, title: '今日最热搞笑视频', searchCount: 890000, category: '娱乐', badge: '', url: '/search?q=今日最热搞笑视频' },
    { id: 'hot_19', rank: 19, title: '陕西油泼面正宗做法', searchCount: 860000, category: '生活', badge: 'hot', url: '/search?q=陕西油泼面正宗做法' },
    { id: 'hot_20', rank: 20, title: '2026年高考倒计时', searchCount: 830000, category: '教育', badge: 'new', url: '/search?q=2026年高考倒计时' },
    { id: 'hot_21', rank: 21, title: '网红打卡地三里屯咖啡', searchCount: 790000, category: '生活', badge: '', url: '/search?q=网红打卡地三里屯咖啡' },
    { id: 'hot_22', rank: 22, title: '国足亚洲杯备战', searchCount: 760000, category: '体育', badge: 'hot', url: '/search?q=国足亚洲杯备战' },
    { id: 'hot_23', rank: 23, title: '电动车续航实测2026', searchCount: 730000, category: '科技', badge: '', url: '/search?q=电动车续航实测2026' },
    { id: 'hot_24', rank: 24, title: '独立音乐人专辑排行', searchCount: 700000, category: '娱乐', badge: 'hot', url: '/search?q=独立音乐人专辑排行' },
    { id: 'hot_25', rank: 25, title: '春笋的100种吃法', searchCount: 680000, category: '生活', badge: '', url: '/search?q=春笋的100种吃法' },
    { id: 'hot_26', rank: 26, title: '明星素颜大比拼', searchCount: 650000, category: '娱乐', badge: 'hot', url: '/search?q=明星素颜大比拼' },
    { id: 'hot_27', rank: 27, title: '国际黄金价格创新高', searchCount: 630000, category: '财经', badge: 'new', url: '/search?q=国际黄金价格创新高' },
    { id: 'hot_28', rank: 28, title: '博物馆文物鉴赏指南', searchCount: 610000, category: '文化', badge: '', url: '/search?q=博物馆文物鉴赏指南' },
    { id: 'hot_29', rank: 29, title: '深圳南山新办公楼空置', searchCount: 590000, category: '财经', badge: 'hot', url: '/search?q=深圳南山新办公楼空置' },
    { id: 'hot_30', rank: 30, title: '东北旅游攻略2026', searchCount: 570000, category: '生活', badge: '', url: '/search?q=东北旅游攻略2026' },
    { id: 'hot_31', rank: 31, title: '手工耿最新发明', searchCount: 550000, category: '娱乐', badge: 'hot', url: '/search?q=手工耿最新发明' },
    { id: 'hot_32', rank: 32, title: '成都IFS屋顶大熊猫', searchCount: 530000, category: '生活', badge: '', url: '/search?q=成都IFS屋顶大熊猫' },
    { id: 'hot_33', rank: 33, title: '国产动画电影票房', searchCount: 510000, category: '娱乐', badge: 'hot', url: '/search?q=国产动画电影票房' },
    { id: 'hot_34', rank: 34, title: '今天天气预报全国', searchCount: 490000, category: '社会', badge: '', url: '/search?q=今天天气预报全国' },
    { id: 'hot_35', rank: 35, title: '减肥最快的运动方式', searchCount: 470000, category: '生活', badge: 'hot', url: '/search?q=减肥最快的运动方式' },
    { id: 'hot_36', rank: 36, title: '上市公司年报发布季', searchCount: 450000, category: '财经', badge: '', url: '/search?q=上市公司年报发布季' },
    { id: 'hot_37', rank: 37, title: '世界读书日推荐书单', searchCount: 430000, category: '文化', badge: 'new', url: '/search?q=世界读书日推荐书单' },
    { id: 'hot_38', rank: 38, title: '海外华人回国路况', searchCount: 410000, category: '社会', badge: '', url: '/search?q=海外华人回国路况' },
    { id: 'hot_39', rank: 39, title: '网络游戏防沉迷新规', searchCount: 390000, category: '科技', badge: 'hot', url: '/search?q=网络游戏防沉迷新规' },
    { id: 'hot_40', rank: 40, title: '中国羽毛球公开赛', searchCount: 370000, category: '体育', badge: '', url: '/search?q=中国羽毛球公开赛' },
    { id: 'hot_41', rank: 41, title: '最受欢迎国产品牌', searchCount: 350000, category: '财经', badge: 'hot', url: '/search?q=最受欢迎国产品牌' },
    { id: 'hot_42', rank: 42, title: '北京通州环球影城攻略', searchCount: 330000, category: '生活', badge: '', url: '/search?q=北京通州环球影城攻略' },
    { id: 'hot_43', rank: 43, title: '国际劳动节假期安排', searchCount: 310000, category: '社会', badge: 'new', url: '/search?q=国际劳动节假期安排' },
    { id: 'hot_44', rank: 44, title: '苹果发布会新品预测', searchCount: 290000, category: '科技', badge: '', url: '/search?q=苹果发布会新品预测' },
    { id: 'hot_45', rank: 45, title: '高铁最新线路开通', searchCount: 270000, category: '社会', badge: 'hot', url: '/search?q=高铁最新线路开通' },
    { id: 'hot_46', rank: 46, title: '大学生创业优秀案例', searchCount: 250000, category: '教育', badge: '', url: '/search?q=大学生创业优秀案例' },
    { id: 'hot_47', rank: 47, title: '中超足球赛季开幕', searchCount: 230000, category: '体育', badge: 'hot', url: '/search?q=中超足球赛季开幕' },
    { id: 'hot_48', rank: 48, title: '夏日防晒霜推荐', searchCount: 210000, category: '生活', badge: '', url: '/search?q=夏日防晒霜推荐' },
    { id: 'hot_49', rank: 49, title: '公务员考试时间表', searchCount: 190000, category: '教育', badge: 'new', url: '/search?q=公务员考试时间表' },
    { id: 'hot_50', rank: 50, title: '国内旅游城市排行榜', searchCount: 170000, category: '生活', badge: '', url: '/search?q=国内旅游城市排行榜' },
  ];

  const topics = {
    topic_1: {
      id: 'topic_1',
      name: '新能源汽车政策',
      readCount: 890000000,
      discussionCount: 456000,
      description: '关于新能源汽车行业政策、补贴、技术发展的讨论',
      hostUserId: null,
      isSuperTopic: false,
    },
    topic_2: {
      id: 'topic_2',
      name: '绿色出行',
      readCount: 320000000,
      discussionCount: 178000,
      description: '倡导绿色环保的出行方式，分享低碳生活',
      hostUserId: null,
      isSuperTopic: false,
    },
    topic_3: {
      id: 'topic_3',
      name: 'AI大模型',
      readCount: 2340000000,
      discussionCount: 1230000,
      description: '人工智能大模型技术、产品评测和行业动态',
      hostUserId: 'user_2',
      isSuperTopic: true,
    },
    topic_4: {
      id: 'topic_4',
      name: '家常菜',
      readCount: 450000000,
      discussionCount: 234000,
      description: '分享简单好吃的家常菜做法',
      hostUserId: 'user_3',
      isSuperTopic: true,
    },
    topic_5: {
      id: 'topic_5',
      name: '美食分享',
      readCount: 1200000000,
      discussionCount: 678000,
      description: '分享各地美食文化，探索舌尖上的中国',
      hostUserId: null,
      isSuperTopic: false,
    },
    topic_6: {
      id: 'topic_6',
      name: '华为',
      readCount: 3400000000,
      discussionCount: 2340000,
      description: '华为官方超话，产品资讯、技术分享',
      hostUserId: 'user_4',
      isSuperTopic: true,
    },
    topic_7: {
      id: 'topic_7',
      name: '洱海骑行',
      readCount: 89000000,
      discussionCount: 45000,
      description: '围绕大理洱海骑行的攻略和游记分享',
      hostUserId: null,
      isSuperTopic: false,
    },
    topic_8: {
      id: 'topic_8',
      name: '云南旅行',
      readCount: 780000000,
      discussionCount: 456000,
      description: '云南旅游攻略、美景分享、行程规划',
      hostUserId: null,
      isSuperTopic: false,
    },
    topic_9: {
      id: 'topic_9',
      name: '繁花',
      readCount: 456000000,
      discussionCount: 234000,
      description: '王家卫执导电视剧《繁花》的剧情讨论',
      hostUserId: null,
      isSuperTopic: false,
    },
    topic_10: {
      id: 'topic_10',
      name: 'CBA总决赛',
      readCount: 890000000,
      discussionCount: 678000,
      description: '中国男子篮球职业联赛总决赛实时动态',
      hostUserId: null,
      isSuperTopic: false,
    },
  };

  const conversations = {
    conv_1: {
      id: 'conv_1',
      participantIds: ['user_current', 'user_6'],
      lastMessageId: 'msg_4',
      lastMessageAt: hoursAgo(1),
      unreadCount: 0,
    },
    conv_2: {
      id: 'conv_2',
      participantIds: ['user_current', 'user_2'],
      lastMessageId: 'msg_8',
      lastMessageAt: hoursAgo(5),
      unreadCount: 2,
    },
    conv_3: {
      id: 'conv_3',
      participantIds: ['user_current', 'user_3'],
      lastMessageId: 'msg_13',
      lastMessageAt: hoursAgo(24),
      unreadCount: 3,
    },
    conv_4: {
      id: 'conv_4',
      participantIds: ['user_current', 'user_9'],
      lastMessageId: 'msg_17',
      lastMessageAt: daysAgo(2),
      unreadCount: 0,
    },
  };

  const messages = {
    msg_1: {
      id: 'msg_1',
      conversationId: 'conv_1',
      senderId: 'user_current',
      receiverId: 'user_6',
      text: '晓雨，上次我发那家咖啡店的位置你找到了吗？',
      createdAt: hoursAgo(3),
      isRead: true,
    },
    msg_2: {
      id: 'msg_2',
      conversationId: 'conv_1',
      senderId: 'user_6',
      receiverId: 'user_current',
      text: '找到了！环境真的很好，拿铁也很好喝！',
      createdAt: hoursAgo(2.5),
      isRead: true,
    },
    msg_3: {
      id: 'msg_3',
      conversationId: 'conv_1',
      senderId: 'user_current',
      receiverId: 'user_6',
      text: '哈哈对吧！下次我们一起去坐坐？',
      createdAt: hoursAgo(2),
      isRead: true,
    },
    msg_4: {
      id: 'msg_4',
      conversationId: 'conv_1',
      senderId: 'user_6',
      receiverId: 'user_current',
      text: '好啊！周末有空的话约起来！',
      createdAt: hoursAgo(1),
      isRead: true,
    },
    msg_5: {
      id: 'msg_5',
      conversationId: 'conv_2',
      senderId: 'user_current',
      receiverId: 'user_2',
      text: '博主你好！能问一下你测试大模型用的是什么评测框架吗？',
      createdAt: hoursAgo(8),
      isRead: true,
    },
    msg_6: {
      id: 'msg_6',
      conversationId: 'conv_2',
      senderId: 'user_2',
      receiverId: 'user_current',
      text: '你好！我用的是自己搭建的评测脚本，基于HumanEval数据集扩展的。',
      createdAt: hoursAgo(7.5),
      isRead: true,
    },
    msg_7: {
      id: 'msg_7',
      conversationId: 'conv_2',
      senderId: 'user_2',
      receiverId: 'user_current',
      text: '完整的评测代码我最近会开源在GitHub上，到时候关注一下！',
      createdAt: hoursAgo(6),
      isRead: false,
    },
    msg_8: {
      id: 'msg_8',
      conversationId: 'conv_2',
      senderId: 'user_2',
      receiverId: 'user_current',
      text: '另外你如果有具体的测试需求，可以告诉我，我可以帮你加入评测集里。',
      createdAt: hoursAgo(5),
      isRead: false,
    },
    msg_9: {
      id: 'msg_9',
      conversationId: 'conv_3',
      senderId: 'user_3',
      receiverId: 'user_current',
      text: '你好！看到你在评论区问了番茄炒蛋的做法，这是我专门整理的详细版配方：',
      createdAt: daysAgo(1),
      isRead: false,
    },
    msg_10: {
      id: 'msg_10',
      conversationId: 'conv_3',
      senderId: 'user_3',
      receiverId: 'user_current',
      text: '食材：鸡蛋3个、番茄2个、葱花适量、盐、白糖各一小勺',
      createdAt: daysAgo(1),
      isRead: false,
    },
    msg_11: {
      id: 'msg_11',
      conversationId: 'conv_3',
      senderId: 'user_3',
      receiverId: 'user_current',
      text: '步骤：1.鸡蛋打散加盐，热锅冷油炒熟盛出；2.番茄入锅炒软出汁；3.加入鸡蛋翻炒；4.加盐、白糖调味；5.撒葱花出锅。',
      createdAt: daysAgo(1),
      isRead: false,
    },
    msg_12: {
      id: 'msg_12',
      conversationId: 'conv_3',
      senderId: 'user_current',
      receiverId: 'user_3',
      text: '谢谢！今天就试试！',
      createdAt: hoursAgo(25),
      isRead: true,
    },
    msg_13: {
      id: 'msg_13',
      conversationId: 'conv_3',
      senderId: 'user_3',
      receiverId: 'user_current',
      text: '做完记得分享给我看！加油👍',
      createdAt: hoursAgo(24),
      isRead: false,
    },
    msg_14: {
      id: 'msg_14',
      conversationId: 'conv_4',
      senderId: 'user_9',
      receiverId: 'user_current',
      text: '你好！我们是高中同班同学吧？李小明？',
      createdAt: daysAgo(3),
      isRead: true,
    },
    msg_15: {
      id: 'msg_15',
      conversationId: 'conv_4',
      senderId: 'user_current',
      receiverId: 'user_9',
      text: '赵小花！是你吗！哈哈哈好久不见！',
      createdAt: daysAgo(3),
      isRead: true,
    },
    msg_16: {
      id: 'msg_16',
      conversationId: 'conv_4',
      senderId: 'user_9',
      receiverId: 'user_current',
      text: '是我！你现在在北京？改天出来聚聚！',
      createdAt: daysAgo(2),
      isRead: true,
    },
    msg_17: {
      id: 'msg_17',
      conversationId: 'conv_4',
      senderId: 'user_current',
      receiverId: 'user_9',
      text: '好啊！五一前后我有时间，到时候约！',
      createdAt: daysAgo(2),
      isRead: true,
    },
  };

  const notifications = [
    {
      id: 'notif_1',
      type: 'like',
      fromUserId: 'user_3',
      postId: 'post_10',
      commentId: null,
      text: '赞了你的微博',
      createdAt: hoursAgo(0.5),
      isRead: false,
    },
    {
      id: 'notif_2',
      type: 'comment',
      fromUserId: 'user_6',
      postId: 'post_10',
      commentId: 'comment_25',
      text: '评论了你的微博：我去过！那家叫"云隐"的咖啡店对吗？',
      createdAt: hoursAgo(1),
      isRead: false,
    },
    {
      id: 'notif_3',
      type: 'like',
      fromUserId: 'user_2',
      postId: 'post_10',
      commentId: null,
      text: '赞了你的微博',
      createdAt: hoursAgo(2),
      isRead: false,
    },
    {
      id: 'notif_4',
      type: 'follow',
      fromUserId: 'user_10',
      postId: null,
      commentId: null,
      text: '关注了你',
      createdAt: hoursAgo(3),
      isRead: false,
    },
    {
      id: 'notif_5',
      type: 'mention',
      fromUserId: 'user_1',
      postId: 'post_1',
      commentId: null,
      text: '在微博中提到了你',
      createdAt: hoursAgo(4),
      isRead: false,
    },
    {
      id: 'notif_6',
      type: 'repost',
      fromUserId: 'user_5',
      postId: 'post_10',
      commentId: null,
      text: '转发了你的微博',
      createdAt: hoursAgo(6),
      isRead: true,
    },
    {
      id: 'notif_7',
      type: 'comment',
      fromUserId: 'user_9',
      postId: 'post_10',
      commentId: null,
      text: '评论了你的微博：好想去三里屯！',
      createdAt: hoursAgo(8),
      isRead: true,
    },
    {
      id: 'notif_8',
      type: 'like',
      fromUserId: 'user_7',
      postId: 'post_10',
      commentId: null,
      text: '赞了你的微博',
      createdAt: hoursAgo(10),
      isRead: true,
    },
    {
      id: 'notif_9',
      type: 'follow',
      fromUserId: 'user_8',
      postId: null,
      commentId: null,
      text: '关注了你',
      createdAt: hoursAgo(12),
      isRead: true,
    },
    {
      id: 'notif_10',
      type: 'repost',
      fromUserId: 'user_11',
      postId: 'post_10',
      commentId: null,
      text: '转发了你的微博',
      createdAt: hoursAgo(16),
      isRead: true,
    },
    {
      id: 'notif_11',
      type: 'comment',
      fromUserId: 'user_4',
      postId: 'post_10',
      commentId: null,
      text: '评论了你的微博：三里屯的咖啡确实不错，华为旗舰店就在附近',
      createdAt: hoursAgo(20),
      isRead: true,
    },
    {
      id: 'notif_12',
      type: 'mention',
      fromUserId: 'user_3',
      postId: 'post_3',
      commentId: null,
      text: '在微博评论中提到了你',
      createdAt: hoursAgo(24),
      isRead: true,
    },
    {
      id: 'notif_13',
      type: 'like',
      fromUserId: 'user_1',
      postId: 'post_10',
      commentId: null,
      text: '赞了你的微博',
      createdAt: daysAgo(2),
      isRead: true,
    },
    {
      id: 'notif_14',
      type: 'system',
      fromUserId: null,
      postId: null,
      commentId: null,
      text: '你的微博已获得100个赞，继续努力创作！',
      createdAt: daysAgo(2),
      isRead: true,
    },
    {
      id: 'notif_15',
      type: 'system',
      fromUserId: null,
      postId: null,
      commentId: null,
      text: '欢迎使用微博网页版！点击探索更多功能。',
      createdAt: daysAgo(3),
      isRead: true,
    },
  ];

  return {
    currentUser: users.user_current,
    users,
    posts,
    comments,
    hotSearches,
    topics,
    followedTopics: ['topic_1', 'topic_3'],
    conversations,
    messages,
    notifications,
    settings: {
      receiveDMs: true,
      commentPermission: 'everyone',
      darkMode: false,
      emailNotifications: true,
      pushNotifications: true,
    },
    ui: {
      feedTab: 'following',
      searchQuery: '',
      selectedPostId: null,
      notificationUnreadCount: 5,
      messageUnreadCount: 5,
    },
  };
}

export function loadState() {
  try {
    const stored = localStorage.getItem(STORAGE_KEY);
    if (stored) {
      return JSON.parse(stored);
    }
  } catch (e) {
    console.error('Failed to load state:', e);
  }
  return null;
}

export function saveState(state) {
  try {
    localStorage.setItem(STORAGE_KEY, JSON.stringify(state));
    // Also sync to server if available
    syncStateToServer(state);
  } catch (e) {
    console.error('Failed to save state:', e);
  }
}

async function syncStateToServer(state) {
  try {
    const params = new URLSearchParams(window.location.search);
    const sid = params.get('sid');
    if (!sid) return;
    await fetch(`/post?sid=${sid}`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ action: 'set_current', state }),
    });
  } catch (e) {
    // Silently fail
  }
}

export function getStateDiff(initialState, currentState) {
  if (!initialState || !currentState) return {};
  const diff = {};

  // Posts diff
  const initialPostIds = new Set(Object.keys(initialState.posts || {}));
  const currentPostIds = new Set(Object.keys(currentState.posts || {}));
  const addedPosts = [...currentPostIds].filter(id => !initialPostIds.has(id));
  const removedPosts = [...initialPostIds].filter(id => !currentPostIds.has(id));
  const changedPosts = [...currentPostIds].filter(id => {
    if (!initialPostIds.has(id)) return false;
    return JSON.stringify(initialState.posts[id]) !== JSON.stringify(currentState.posts[id]);
  });
  if (addedPosts.length || removedPosts.length || changedPosts.length) {
    diff.posts = { added: addedPosts, removed: removedPosts, changed: changedPosts };
  }

  // Comments diff
  const initCommentIds = new Set(Object.keys(initialState.comments || {}));
  const currCommentIds = new Set(Object.keys(currentState.comments || {}));
  const addedComments = [...currCommentIds].filter(id => !initCommentIds.has(id));
  if (addedComments.length) diff.comments = { added: addedComments };

  // Follow changes
  const followChanges = [];
  for (const [uid, cu] of Object.entries(currentState.users || {})) {
    const iu = (initialState.users || {})[uid];
    if (iu && iu.isFollowing !== cu.isFollowing) {
      followChanges.push({ userId: uid, isFollowing: cu.isFollowing });
    }
  }
  if (followChanges.length) diff.followChanges = followChanges;

  // Notification changes
  const readNotifs = (currentState.notifications || [])
    .filter(cn => {
      const inotif = (initialState.notifications || []).find(n => n.id === cn.id);
      return inotif && !inotif.isRead && cn.isRead;
    })
    .map(n => n.id);
  if (readNotifs.length) diff.readNotifications = readNotifs;

  // Message changes
  const addedMessages = Object.keys(currentState.messages || {}).filter(
    id => !(initialState.messages || {})[id]
  );
  if (addedMessages.length) diff.messages = { added: addedMessages };

  // Settings changes
  const initSettings = initialState.settings || {};
  const currSettings = currentState.settings || {};
  const settingChanges = {};
  for (const key of Object.keys(currSettings)) {
    if (initSettings[key] !== currSettings[key]) {
      settingChanges[key] = { old: initSettings[key], new: currSettings[key] };
    }
  }
  if (Object.keys(settingChanges).length) diff.settings = settingChanges;

  // FollowedTopics changes
  const initTopics = new Set(initialState.followedTopics || []);
  const currTopics = new Set(currentState.followedTopics || []);
  const followedAdded = [...currTopics].filter(id => !initTopics.has(id));
  const followedRemoved = [...initTopics].filter(id => !currTopics.has(id));
  if (followedAdded.length || followedRemoved.length) {
    diff.followedTopics = { added: followedAdded, removed: followedRemoved };
  }

  // Profile changes
  const initUser = (initialState.users || {})['user_current'] || {};
  const currUser = (currentState.users || {})['user_current'] || {};
  const profileFields = ['screenName', 'bio', 'location'];
  const profileChanges = {};
  for (const f of profileFields) {
    if (initUser[f] !== currUser[f]) profileChanges[f] = { old: initUser[f], new: currUser[f] };
  }
  if (Object.keys(profileChanges).length) diff.profileChanges = profileChanges;

  return diff;
}
