#!/usr/bin/env bash
# Generate (or regenerate) an nginx reverse-proxy config that fans out
# *.<domain> -> each mock's local port. Idempotent; safe to re-run.
#
# Usage:
#   sudo bash gen-nginx.sh --domain mocks.example.com
#   sudo bash gen-nginx.sh --domain mocks.example.com --base-port 18000 \
#                         --repo-dir /opt/CUA-Gym-Hub
#
# After running:
#   1. Point a wildcard A record  *.<domain>  at this VM's public IP.
#   2. Allow port 80 (and 443) in the Volcano security group.
#   3. For TLS:  sudo certbot --nginx -d "*.<domain>"
#
# Subdomain naming rule:
#   foo_mock          ->  foo.<domain>
#   Canvas-LMS_mock   ->  canvas-lms.<domain>
#   aws_console_mock  ->  aws-console.<domain>

set -euo pipefail

REPO_DIR="/opt/CUA-Gym-Hub"
BASE_PORT=8000
DOMAIN=""
CONF_PATH="/etc/nginx/sites-available/cua-gym-hub.conf"
LINK_PATH="/etc/nginx/sites-enabled/cua-gym-hub.conf"
STDOUT_ONLY=false

while [[ $# -gt 0 ]]; do
  case "$1" in
    --repo-dir)    REPO_DIR="$2"; shift 2 ;;
    --base-port)   BASE_PORT="$2"; shift 2 ;;
    --domain)      DOMAIN="$2"; shift 2 ;;
    --conf-path)   CONF_PATH="$2"; shift 2 ;;
    --stdout)      STDOUT_ONLY=true; shift ;;
    -h|--help)
      sed -n '1,/^set -euo/p' "$0" | sed '$d' | sed 's/^# \{0,1\}//'
      exit 0 ;;
    *) echo "Unknown arg: $1" >&2; exit 2 ;;
  esac
done

[[ -n "$DOMAIN" ]] || { echo "--domain is required" >&2; exit 2; }
[[ -d "$REPO_DIR/websites" ]] || { echo "websites/ not found under $REPO_DIR" >&2; exit 2; }

if ! $STDOUT_ONLY && [[ $EUID -ne 0 ]]; then
  echo "Need root to write $CONF_PATH; re-run with sudo, or use --stdout to preview." >&2
  exit 2
fi

generate() {
  echo "# Auto-generated by deploy/volcano/gen-nginx.sh"
  echo "# Wildcard host -> local port map for CUA-Gym-Hub mocks."
  echo ""
  echo "map \$host \$cua_mock_port {"
  echo "    default 0;"
  local i=0
  for d in $(ls -1 "$REPO_DIR/websites" | sort); do
    [[ -d "$REPO_DIR/websites/$d" ]] || continue
    [[ "$d" == *_mock ]] || continue
    local sub
    sub="$(echo "${d%_mock}" | tr '[:upper:]_' '[:lower:]-')"
    printf "    \"%s.%s\" %d;\n" "$sub" "$DOMAIN" "$((BASE_PORT + i))"
    i=$((i + 1))
  done
  echo "}"
  echo ""
  echo "server {"
  echo "    listen 80;"
  echo "    server_name *.${DOMAIN};"
  echo ""
  echo "    if (\$cua_mock_port = 0) { return 404; }"
  echo ""
  echo "    client_max_body_size 50m;"
  echo ""
  echo "    location / {"
  echo "        proxy_pass http://127.0.0.1:\$cua_mock_port;"
  echo "        proxy_http_version 1.1;"
  echo "        proxy_set_header Host \$host;"
  echo "        proxy_set_header X-Real-IP \$remote_addr;"
  echo "        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;"
  echo "        proxy_set_header X-Forwarded-Proto \$scheme;"
  echo "        proxy_read_timeout 120s;"
  echo "    }"
  echo "}"
}

if $STDOUT_ONLY; then
  generate
  exit 0
fi

mkdir -p "$(dirname "$CONF_PATH")"
generate > "$CONF_PATH"
ln -sf "$CONF_PATH" "$LINK_PATH"
rm -f /etc/nginx/sites-enabled/default

if command -v nginx >/dev/null; then
  nginx -t
  systemctl reload nginx
  echo "nginx reloaded. Wildcard *.${DOMAIN} now proxies to ports ${BASE_PORT}-$((BASE_PORT + 97))."
else
  echo "nginx not installed; conf written to $CONF_PATH but not enabled." >&2
fi
