// Xeishu Mock — Data Manager
// Full seed data for all entities

const NOW = Date.now();
const DAY = 86400000;
const HOUR = 3600000;

// Helper to get timestamp relative to now
function ts(daysAgo = 0, hoursAgo = 0, minutesAgo = 0) {
  return NOW - daysAgo * DAY - hoursAgo * HOUR - minutesAgo * 60000;
}

// Get current week's Monday
function getWeekStart() {
  const d = new Date();
  const day = d.getDay();
  const diff = d.getDate() - day + (day === 0 ? -6 : 1);
  d.setDate(diff);
  d.setHours(0, 0, 0, 0);
  return d.getTime();
}

export function createInitialData() {
  const weekStart = getWeekStart();

  // ─── USERS ───
  const users = [
    {
      id: 'user_1',
      name: '张明',
      englishName: 'Zhang Ming',
      avatar: '',
      avatarColor: '#3370FF',
      initials: '张',
      email: 'zhangming@bytedance.com',
      phone: '138****5678',
      department: '产品研发部',
      title: '高级产品经理',
      status: 'online',
      statusText: '',
      statusEmoji: '',
      isCurrentUser: true,
    },
    {
      id: 'user_2',
      name: '李薇',
      englishName: 'Li Wei',
      avatar: '',
      avatarColor: '#FF7D00',
      initials: '李',
      email: 'liwei@bytedance.com',
      phone: '139****1234',
      department: '设计部',
      title: 'UI设计师',
      status: 'online',
      statusText: '设计中',
      statusEmoji: '🎨',
      isCurrentUser: false,
    },
    {
      id: 'user_3',
      name: '王浩',
      englishName: 'Wang Hao',
      avatar: '',
      avatarColor: '#34C724',
      initials: '王',
      email: 'wanghao@bytedance.com',
      phone: '135****9876',
      department: '技术部',
      title: '前端工程师',
      status: 'busy',
      statusText: '开发中，勿扰',
      statusEmoji: '💻',
      isCurrentUser: false,
    },
    {
      id: 'user_4',
      name: '赵艺',
      englishName: 'Zhao Yi',
      avatar: '',
      avatarColor: '#9254DE',
      initials: '赵',
      email: 'zhaoyi@bytedance.com',
      phone: '136****4567',
      department: '市场部',
      title: '市场经理',
      status: 'online',
      statusText: '',
      statusEmoji: '',
      isCurrentUser: false,
    },
    {
      id: 'user_5',
      name: '陈丽',
      englishName: 'Chen Li',
      avatar: '',
      avatarColor: '#F54A45',
      initials: '陈',
      email: 'chenli@bytedance.com',
      phone: '137****3456',
      department: '人事部',
      title: 'HR经理',
      status: 'away',
      statusText: '午休',
      statusEmoji: '😴',
      isCurrentUser: false,
    },
    {
      id: 'user_6',
      name: '刘洋',
      englishName: 'Liu Yang',
      avatar: '',
      avatarColor: '#13C2C2',
      initials: '刘',
      email: 'liuyang@bytedance.com',
      phone: '133****7890',
      department: '技术部',
      title: '后端工程师',
      status: 'online',
      statusText: '',
      statusEmoji: '',
      isCurrentUser: false,
    },
    {
      id: 'user_7',
      name: '周思远',
      englishName: 'Zhou Siyuan',
      avatar: '',
      avatarColor: '#FA8C16',
      initials: '周',
      email: 'zhousiyuan@bytedance.com',
      phone: '131****2345',
      department: '产品研发部',
      title: '产品总监',
      status: 'busy',
      statusText: '会议中',
      statusEmoji: '📅',
      isCurrentUser: false,
    },
    {
      id: 'user_8',
      name: '林小雨',
      englishName: 'Lin Xiaoyu',
      avatar: '',
      avatarColor: '#EB2F96',
      initials: '林',
      email: 'linxiaoyu@bytedance.com',
      phone: '130****6789',
      department: '设计部',
      title: '设计总监',
      status: 'offline',
      statusText: '',
      statusEmoji: '',
      isCurrentUser: false,
    },
    {
      id: 'user_9',
      name: '孙凯',
      englishName: 'Sun Kai',
      avatar: '',
      avatarColor: '#2B5FD9',
      initials: '孙',
      email: 'sunkai@bytedance.com',
      phone: '132****8901',
      department: '技术部',
      title: '测试工程师',
      status: 'online',
      statusText: '',
      statusEmoji: '',
      isCurrentUser: false,
    },
    {
      id: 'user_10',
      name: '吴静',
      englishName: 'Wu Jing',
      avatar: '',
      avatarColor: '#722ED1',
      initials: '吴',
      email: 'wujing@bytedance.com',
      phone: '134****5612',
      department: '产品研发部',
      title: '交互设计师',
      status: 'online',
      statusText: '写文档中',
      statusEmoji: '📝',
      isCurrentUser: false,
    },
    {
      id: 'user_11',
      name: '郑磊',
      englishName: 'Zheng Lei',
      avatar: '',
      avatarColor: '#08979C',
      initials: '郑',
      email: 'zhenglei@bytedance.com',
      phone: '186****3344',
      department: '市场部',
      title: '运营专员',
      status: 'away',
      statusText: '出差中',
      statusEmoji: '✈️',
      isCurrentUser: false,
    },
    {
      id: 'user_12',
      name: '黄敏',
      englishName: 'Huang Min',
      avatar: '',
      avatarColor: '#D48806',
      initials: '黄',
      email: 'huangmin@bytedance.com',
      phone: '158****7788',
      department: '人事部',
      title: '招聘专员',
      status: 'offline',
      statusText: '',
      statusEmoji: '',
      isCurrentUser: false,
    },
    {
      id: 'user_13',
      name: '杨帆',
      englishName: 'Yang Fan',
      avatar: '',
      avatarColor: '#CF1322',
      initials: '杨',
      email: 'yangfan@bytedance.com',
      phone: '177****9900',
      department: '技术部',
      title: '架构师',
      status: 'busy',
      statusText: '代码review中',
      statusEmoji: '🔍',
      isCurrentUser: false,
    },
  ];

  // ─── DEPARTMENTS ───
  const departments = [
    { id: 'dept_0', name: '公司总部', parentId: null, memberIds: ['user_1','user_2','user_3','user_4','user_5','user_6','user_7','user_8','user_9','user_10','user_11','user_12','user_13'], headId: 'user_7' },
    { id: 'dept_1', name: '产品研发部', parentId: 'dept_0', memberIds: ['user_1', 'user_7', 'user_10'], headId: 'user_7' },
    { id: 'dept_2', name: '技术部', parentId: 'dept_0', memberIds: ['user_3', 'user_6', 'user_9', 'user_13'], headId: 'user_13' },
    { id: 'dept_3', name: '设计部', parentId: 'dept_0', memberIds: ['user_2', 'user_8'], headId: 'user_8' },
    { id: 'dept_4', name: '市场部', parentId: 'dept_0', memberIds: ['user_4', 'user_11'], headId: 'user_4' },
    { id: 'dept_5', name: '人事部', parentId: 'dept_0', memberIds: ['user_5', 'user_12'], headId: 'user_5' },
  ];

  // ─── CONVERSATIONS ───
  const conversations = [
    {
      id: 'conv_1',
      type: 'group',
      name: '产品研发群',
      avatar: '',
      memberCount: 6,
      members: ['user_1', 'user_2', 'user_3', 'user_6', 'user_7', 'user_8'],
      lastMessage: { content: '@张明 文档已更新，请查收', senderId: 'user_7', timestamp: ts(0, 0, 5) },
      unreadCount: 2,
      isPinned: true,
      isMuted: false,
      isDone: false,
      topNotice: 'Q2 产品规划方案已发布，请大家查阅并提供反馈 📋',
      labels: [],
      createdAt: ts(30),
    },
    {
      id: 'conv_2',
      type: 'group',
      name: 'Q2 OKR 讨论',
      avatar: '',
      memberCount: 8,
      members: ['user_1', 'user_2', 'user_3', 'user_4', 'user_5', 'user_6', 'user_7', 'user_8'],
      lastMessage: { content: '今天下午3点开会讨论OKR进展', senderId: 'user_7', timestamp: ts(0, 2) },
      unreadCount: 5,
      isPinned: true,
      isMuted: false,
      isDone: false,
      topNotice: null,
      labels: [],
      createdAt: ts(60),
    },
    {
      id: 'conv_3',
      type: 'group',
      name: '市场部',
      avatar: '',
      memberCount: 15,
      members: ['user_1', 'user_4', 'user_5'],
      lastMessage: { content: '好的，明天上午开会讨论', senderId: 'user_4', timestamp: ts(0, 3) },
      unreadCount: 0,
      isPinned: false,
      isMuted: false,
      isDone: false,
      topNotice: null,
      labels: [],
      createdAt: ts(90),
    },
    {
      id: 'conv_4',
      type: 'group',
      name: '全员群',
      avatar: '',
      memberCount: 30,
      members: ['user_1', 'user_2', 'user_3', 'user_4', 'user_5', 'user_6', 'user_7', 'user_8'],
      lastMessage: { content: '通知：本周五团建活动，请大家准时参加！', senderId: 'user_5', timestamp: ts(1) },
      unreadCount: 1,
      isPinned: false,
      isMuted: true,
      isDone: false,
      topNotice: null,
      labels: [],
      createdAt: ts(180),
    },
    {
      id: 'conv_5',
      type: 'group',
      name: '项目A-冲刺计划',
      avatar: '',
      memberCount: 4,
      members: ['user_1', 'user_3', 'user_6', 'user_7'],
      lastMessage: { content: '冲刺计划已更新，请查看最新排期', senderId: 'user_3', timestamp: ts(1, 2) },
      unreadCount: 0,
      isPinned: false,
      isMuted: false,
      isDone: false,
      topNotice: null,
      labels: [],
      createdAt: ts(14),
    },
    {
      id: 'conv_6',
      type: 'direct',
      name: null,
      avatar: '',
      memberCount: 2,
      members: ['user_1', 'user_2'],
      lastMessage: { content: '设计稿已发给你，请查收 ✅', senderId: 'user_2', timestamp: ts(0, 1) },
      unreadCount: 0,
      isPinned: false,
      isMuted: false,
      isDone: false,
      topNotice: null,
      labels: [],
      createdAt: ts(20),
    },
    {
      id: 'conv_7',
      type: 'direct',
      name: null,
      avatar: '',
      memberCount: 2,
      members: ['user_1', 'user_3'],
      lastMessage: { content: '好的，我来处理这个bug', senderId: 'user_3', timestamp: ts(0, 4) },
      unreadCount: 0,
      isPinned: false,
      isMuted: false,
      isDone: false,
      topNotice: null,
      labels: [],
      createdAt: ts(15),
    },
    {
      id: 'conv_8',
      type: 'direct',
      name: null,
      avatar: '',
      memberCount: 2,
      members: ['user_1', 'user_4'],
      lastMessage: { content: '市场活动方案已提交审批', senderId: 'user_4', timestamp: ts(1, 1) },
      unreadCount: 0,
      isPinned: false,
      isMuted: false,
      isDone: false,
      topNotice: null,
      labels: [],
      createdAt: ts(25),
    },
    {
      id: 'conv_9',
      type: 'direct',
      name: null,
      avatar: '',
      memberCount: 2,
      members: ['user_1', 'user_7'],
      lastMessage: { content: '明天1:1会议，我们聊聊Q2规划', senderId: 'user_7', timestamp: ts(0, 6) },
      unreadCount: 0,
      isPinned: false,
      isMuted: false,
      isDone: false,
      topNotice: null,
      labels: [],
      createdAt: ts(40),
    },
    {
      id: 'conv_10',
      type: 'direct',
      name: null,
      avatar: '',
      memberCount: 2,
      members: ['user_1', 'user_8'],
      lastMessage: { content: '设计规范文档我已经更新了', senderId: 'user_8', timestamp: ts(2) },
      unreadCount: 0,
      isPinned: false,
      isMuted: false,
      isDone: false,
      topNotice: null,
      labels: [],
      createdAt: ts(35),
    },
    {
      id: 'conv_bot1',
      type: 'bot',
      name: '飞书助手',
      avatar: '',
      memberCount: 1,
      members: ['user_1'],
      lastMessage: { content: '您有一个新的日历邀请待处理', senderId: 'bot_feishu', timestamp: ts(0, 8) },
      unreadCount: 1,
      isPinned: false,
      isMuted: false,
      isDone: false,
      topNotice: null,
      labels: [],
      createdAt: ts(100),
    },
    {
      id: 'conv_bot2',
      type: 'bot',
      name: '审批通知',
      avatar: '',
      memberCount: 1,
      members: ['user_1'],
      lastMessage: { content: '您有一条待审批申请', senderId: 'bot_approval', timestamp: ts(0, 12) },
      unreadCount: 0,
      isPinned: false,
      isMuted: false,
      isDone: false,
      topNotice: null,
      labels: [],
      createdAt: ts(100),
    },
  ];

  // ─── MESSAGES ───
  const messages = {
    conv_1: [
      {
        id: 'msg_1_1',
        conversationId: 'conv_1',
        senderId: 'user_7',
        content: '大家好，Q2 产品规划方案已经整理好了，请大家查看并提供意见 📋',
        contentType: 'text',
        timestamp: ts(1, 10),
        isEdited: false,
        reactions: [{ emoji: '👍', userIds: ['user_1', 'user_2', 'user_3'] }],
        threadId: null,
        threadCount: 3,
        threadLastReply: ts(1, 8),
        replyTo: null,
        mentions: [],
        isRead: true,
        isPinned: false,
        attachments: [],
        card: null,
      },
      {
        id: 'msg_1_1_r1',
        conversationId: 'conv_1',
        senderId: 'user_1',
        content: '好的，我今天下午看完了，整体方向没问题，有几个细节可以再讨论一下',
        contentType: 'text',
        timestamp: ts(1, 9),
        isEdited: false,
        reactions: [],
        threadId: 'msg_1_1',
        threadCount: 0,
        threadLastReply: null,
        replyTo: null,
        mentions: [],
        isRead: true,
        isPinned: false,
        attachments: [],
        card: null,
      },
      {
        id: 'msg_1_1_r2',
        conversationId: 'conv_1',
        senderId: 'user_2',
        content: '设计部分我来负责，可以提前和张明对齐一下需求',
        contentType: 'text',
        timestamp: ts(1, 8, 30),
        isEdited: false,
        reactions: [],
        threadId: 'msg_1_1',
        threadCount: 0,
        threadLastReply: null,
        replyTo: null,
        mentions: ['user_1'],
        isRead: true,
        isPinned: false,
        attachments: [],
        card: null,
      },
      {
        id: 'msg_1_1_r3',
        conversationId: 'conv_1',
        senderId: 'user_3',
        content: '技术实现上没什么问题，我们可以按这个排期来',
        contentType: 'text',
        timestamp: ts(1, 8),
        isEdited: false,
        reactions: [{ emoji: '✅', userIds: ['user_7'] }],
        threadId: 'msg_1_1',
        threadCount: 0,
        threadLastReply: null,
        replyTo: null,
        mentions: [],
        isRead: true,
        isPinned: false,
        attachments: [],
        card: null,
      },
      {
        id: 'msg_1_2',
        conversationId: 'conv_1',
        senderId: 'system',
        content: '王浩 加入了群聊',
        contentType: 'system',
        timestamp: ts(1, 7),
        isEdited: false,
        reactions: [],
        threadId: null,
        threadCount: 0,
        threadLastReply: null,
        replyTo: null,
        mentions: [],
        isRead: true,
        isPinned: false,
        attachments: [],
        card: null,
      },
      {
        id: 'msg_1_3',
        conversationId: 'conv_1',
        senderId: 'user_3',
        content: '大家好，我是王浩，前端工程师，很高兴加入这个群 😊',
        contentType: 'text',
        timestamp: ts(1, 6, 50),
        isEdited: false,
        reactions: [{ emoji: '👋', userIds: ['user_1', 'user_2', 'user_7'] }],
        threadId: null,
        threadCount: 0,
        threadLastReply: null,
        replyTo: null,
        mentions: [],
        isRead: true,
        isPinned: false,
        attachments: [],
        card: null,
      },
      {
        id: 'msg_1_4',
        conversationId: 'conv_1',
        senderId: 'user_1',
        content: '项目A的需求文档我已经更新到最新版本了，主要改动是第三章的用户旅程部分，大家抽时间看一下',
        contentType: 'text',
        timestamp: ts(0, 5),
        isEdited: false,
        reactions: [{ emoji: '👍', userIds: ['user_7', 'user_3'] }, { emoji: '🎉', userIds: ['user_2'] }],
        threadId: null,
        threadCount: 0,
        threadLastReply: null,
        replyTo: null,
        mentions: [],
        isRead: true,
        isPinned: false,
        attachments: [],
        card: null,
      },
      {
        id: 'msg_1_5',
        conversationId: 'conv_1',
        senderId: 'user_2',
        content: '收到，我来看看设计这边需要配合的地方',
        contentType: 'text',
        timestamp: ts(0, 4, 50),
        isEdited: false,
        reactions: [],
        threadId: null,
        threadCount: 0,
        threadLastReply: null,
        replyTo: null,
        mentions: [],
        isRead: true,
        isPinned: false,
        attachments: [],
        card: null,
      },
      {
        id: 'msg_1_6',
        conversationId: 'conv_1',
        senderId: 'user_6',
        content: '后端接口设计文档我今天会发出来，预计明天可以联调',
        contentType: 'text',
        timestamp: ts(0, 3),
        isEdited: false,
        reactions: [],
        threadId: null,
        threadCount: 0,
        threadLastReply: null,
        replyTo: null,
        mentions: [],
        isRead: true,
        isPinned: false,
        attachments: [],
        card: null,
      },
      {
        id: 'msg_1_7',
        conversationId: 'conv_1',
        senderId: 'user_1',
        content: '@王浩 @刘洋 联调时间我们协调一下，明天下午2点可以吗？',
        contentType: 'text',
        timestamp: ts(0, 2, 30),
        isEdited: false,
        reactions: [],
        threadId: null,
        threadCount: 0,
        threadLastReply: null,
        replyTo: null,
        mentions: ['user_3', 'user_6'],
        isRead: true,
        isPinned: false,
        attachments: [],
        card: null,
      },
      {
        id: 'msg_1_8',
        conversationId: 'conv_1',
        senderId: 'user_3',
        content: '可以的，我2点有空',
        contentType: 'text',
        timestamp: ts(0, 2, 20),
        isEdited: false,
        reactions: [{ emoji: '✅', userIds: ['user_1'] }],
        threadId: null,
        threadCount: 0,
        threadLastReply: null,
        replyTo: null,
        mentions: [],
        isRead: true,
        isPinned: false,
        attachments: [],
        card: null,
      },
      {
        id: 'msg_1_9',
        conversationId: 'conv_1',
        senderId: 'user_6',
        content: '没问题，2点见',
        contentType: 'text',
        timestamp: ts(0, 2, 10),
        isEdited: false,
        reactions: [],
        threadId: null,
        threadCount: 0,
        threadLastReply: null,
        replyTo: null,
        mentions: [],
        isRead: true,
        isPinned: false,
        attachments: [],
        card: null,
      },
      {
        id: 'msg_1_10',
        conversationId: 'conv_1',
        senderId: 'user_7',
        content: '@张明 文档已更新，请查收',
        contentType: 'text',
        timestamp: ts(0, 0, 5),
        isEdited: false,
        reactions: [],
        threadId: null,
        threadCount: 0,
        threadLastReply: null,
        replyTo: null,
        mentions: ['user_1'],
        isRead: false,
        isPinned: false,
        attachments: [],
        card: null,
      },
      {
        id: 'msg_1_11',
        conversationId: 'conv_1',
        senderId: 'user_2',
        content: '',
        contentType: 'image',
        filename: '产品原型图_v3.png',
        imageUrl: '',
        timestamp: ts(0, 0, 3),
        isEdited: false,
        reactions: [{ emoji: '👍', userIds: ['user_1', 'user_3'] }],
        threadId: null,
        threadCount: 0,
        threadLastReply: null,
        replyTo: null,
        mentions: [],
        isRead: false,
        isPinned: false,
        attachments: [],
        card: null,
      },
      {
        id: 'msg_1_12',
        conversationId: 'conv_1',
        senderId: 'user_3',
        content: '',
        contentType: 'file',
        filename: '技术评审报告_2024Q2.docx',
        filesize: '2.4 MB',
        timestamp: ts(0, 0, 1),
        isEdited: false,
        reactions: [],
        threadId: null,
        threadCount: 0,
        threadLastReply: null,
        replyTo: null,
        mentions: [],
        isRead: false,
        isPinned: false,
        attachments: [],
        card: null,
      },
    ],

    conv_2: [
      {
        id: 'msg_2_1',
        conversationId: 'conv_2',
        senderId: 'user_7',
        content: '大家好，今天我们来回顾一下Q2 OKR的完成情况',
        contentType: 'text',
        timestamp: ts(2, 10),
        isEdited: false,
        reactions: [],
        threadId: null,
        threadCount: 0,
        threadLastReply: null,
        replyTo: null,
        mentions: [],
        isRead: true,
        isPinned: false,
        attachments: [],
        card: null,
      },
      {
        id: 'msg_2_2',
        conversationId: 'conv_2',
        senderId: 'user_1',
        content: '产品这边目标完成度大概70%，主要卡在用户调研数据的分析上',
        contentType: 'text',
        timestamp: ts(2, 9),
        isEdited: false,
        reactions: [],
        threadId: null,
        threadCount: 0,
        threadLastReply: null,
        replyTo: null,
        mentions: [],
        isRead: true,
        isPinned: false,
        attachments: [],
        card: null,
      },
      {
        id: 'msg_2_3',
        conversationId: 'conv_2',
        senderId: 'user_4',
        content: '市场部这边活动已经全部完成，ROI超出预期20%',
        contentType: 'text',
        timestamp: ts(2, 8),
        isEdited: false,
        reactions: [{ emoji: '🎉', userIds: ['user_1', 'user_7', 'user_5'] }],
        threadId: null,
        threadCount: 0,
        threadLastReply: null,
        replyTo: null,
        mentions: [],
        isRead: true,
        isPinned: false,
        attachments: [],
        card: null,
      },
      {
        id: 'msg_2_4',
        conversationId: 'conv_2',
        senderId: 'user_3',
        content: '技术侧三个项目都按时上线，性能指标达标',
        contentType: 'text',
        timestamp: ts(1, 5),
        isEdited: false,
        reactions: [{ emoji: '👍', userIds: ['user_7'] }],
        threadId: null,
        threadCount: 0,
        threadLastReply: null,
        replyTo: null,
        mentions: [],
        isRead: true,
        isPinned: false,
        attachments: [],
        card: null,
      },
      {
        id: 'msg_2_5',
        conversationId: 'conv_2',
        senderId: 'user_7',
        content: '今天下午3点开会讨论OKR进展，请大家准时参加',
        contentType: 'text',
        timestamp: ts(0, 2),
        isEdited: false,
        reactions: [],
        threadId: null,
        threadCount: 0,
        threadLastReply: null,
        replyTo: null,
        mentions: [],
        isRead: false,
        isPinned: false,
        attachments: [],
        card: null,
      },
    ],

    conv_3: [
      {
        id: 'msg_3_1',
        conversationId: 'conv_3',
        senderId: 'user_4',
        content: '市场部本月活动预算已审批通过，大家可以开始筹备了',
        contentType: 'text',
        timestamp: ts(1, 5),
        isEdited: false,
        reactions: [],
        threadId: null,
        threadCount: 0,
        threadLastReply: null,
        replyTo: null,
        mentions: [],
        isRead: true,
        isPinned: false,
        attachments: [],
        card: null,
      },
      {
        id: 'msg_3_2',
        conversationId: 'conv_3',
        senderId: 'user_1',
        content: '好的，我们可以先制定一个详细的方案',
        contentType: 'text',
        timestamp: ts(0, 5),
        isEdited: false,
        reactions: [],
        threadId: null,
        threadCount: 0,
        threadLastReply: null,
        replyTo: null,
        mentions: [],
        isRead: true,
        isPinned: false,
        attachments: [],
        card: null,
      },
      {
        id: 'msg_3_3',
        conversationId: 'conv_3',
        senderId: 'user_4',
        content: '好的，明天上午开会讨论',
        contentType: 'text',
        timestamp: ts(0, 3),
        isEdited: false,
        reactions: [],
        threadId: null,
        threadCount: 0,
        threadLastReply: null,
        replyTo: null,
        mentions: [],
        isRead: true,
        isPinned: false,
        attachments: [],
        card: null,
      },
    ],

    conv_4: [
      {
        id: 'msg_4_1',
        conversationId: 'conv_4',
        senderId: 'user_5',
        content: '通知：本周五下午3点团建活动，地点：公司楼下餐厅，请大家准时参加！',
        contentType: 'text',
        timestamp: ts(1),
        isEdited: false,
        reactions: [{ emoji: '🎉', userIds: ['user_1', 'user_2', 'user_3'] }],
        threadId: null,
        threadCount: 0,
        threadLastReply: null,
        replyTo: null,
        mentions: [],
        isRead: false,
        isPinned: false,
        attachments: [],
        card: null,
      },
    ],

    conv_5: [
      {
        id: 'msg_5_1',
        conversationId: 'conv_5',
        senderId: 'user_1',
        content: '项目A当前冲刺剩余3个故事点，预计本周五完成',
        contentType: 'text',
        timestamp: ts(2, 8),
        isEdited: false,
        reactions: [],
        threadId: null,
        threadCount: 0,
        threadLastReply: null,
        replyTo: null,
        mentions: [],
        isRead: true,
        isPinned: false,
        attachments: [],
        card: null,
      },
      {
        id: 'msg_5_2',
        conversationId: 'conv_5',
        senderId: 'user_3',
        content: '前端任务已全部领取，今天可以开始开发',
        contentType: 'text',
        timestamp: ts(2, 7),
        isEdited: false,
        reactions: [],
        threadId: null,
        threadCount: 0,
        threadLastReply: null,
        replyTo: null,
        mentions: [],
        isRead: true,
        isPinned: false,
        attachments: [],
        card: null,
      },
      {
        id: 'msg_5_3',
        conversationId: 'conv_5',
        senderId: 'user_3',
        content: '冲刺计划已更新，请查看最新排期',
        contentType: 'text',
        timestamp: ts(1, 2),
        isEdited: false,
        reactions: [],
        threadId: null,
        threadCount: 0,
        threadLastReply: null,
        replyTo: null,
        mentions: [],
        isRead: true,
        isPinned: false,
        attachments: [],
        card: null,
      },
    ],

    conv_6: [
      {
        id: 'msg_6_1',
        conversationId: 'conv_6',
        senderId: 'user_1',
        content: '李薇，新版本的产品设计稿你看了吗？有什么想法？',
        contentType: 'text',
        timestamp: ts(0, 3),
        isEdited: false,
        reactions: [],
        threadId: null,
        threadCount: 0,
        threadLastReply: null,
        replyTo: null,
        mentions: [],
        isRead: true,
        isPinned: false,
        attachments: [],
        card: null,
      },
      {
        id: 'msg_6_2',
        conversationId: 'conv_6',
        senderId: 'user_2',
        content: '看了！整体风格很不错，导航栏的设计我有一些优化建议，稍后发给你',
        contentType: 'text',
        timestamp: ts(0, 2, 30),
        isEdited: false,
        reactions: [],
        threadId: null,
        threadCount: 0,
        threadLastReply: null,
        replyTo: null,
        mentions: [],
        isRead: true,
        isPinned: false,
        attachments: [],
        card: null,
      },
      {
        id: 'msg_6_3',
        conversationId: 'conv_6',
        senderId: 'user_2',
        content: '设计稿已发给你，请查收 ✅',
        contentType: 'text',
        timestamp: ts(0, 1),
        isEdited: false,
        reactions: [],
        threadId: null,
        threadCount: 0,
        threadLastReply: null,
        replyTo: null,
        mentions: [],
        isRead: true,
        isPinned: false,
        attachments: [],
        card: null,
      },
    ],

    conv_7: [
      {
        id: 'msg_7_1',
        conversationId: 'conv_7',
        senderId: 'user_1',
        content: '王浩，登录页面有个样式bug，在Safari上显示不对',
        contentType: 'text',
        timestamp: ts(0, 6),
        isEdited: false,
        reactions: [],
        threadId: null,
        threadCount: 0,
        threadLastReply: null,
        replyTo: null,
        mentions: [],
        isRead: true,
        isPinned: false,
        attachments: [],
        card: null,
      },
      {
        id: 'msg_7_2',
        conversationId: 'conv_7',
        senderId: 'user_3',
        content: '好的，我来处理这个bug，今天内修复',
        contentType: 'text',
        timestamp: ts(0, 4),
        isEdited: false,
        reactions: [],
        threadId: null,
        threadCount: 0,
        threadLastReply: null,
        replyTo: null,
        mentions: [],
        isRead: true,
        isPinned: false,
        attachments: [],
        card: null,
      },
    ],

    conv_8: [
      {
        id: 'msg_8_1',
        conversationId: 'conv_8',
        senderId: 'user_1',
        content: '赵艺，Q2市场活动方案我看完了，内容很充实，可以提交审批了',
        contentType: 'text',
        timestamp: ts(1, 3),
        isEdited: false,
        reactions: [],
        threadId: null,
        threadCount: 0,
        threadLastReply: null,
        replyTo: null,
        mentions: [],
        isRead: true,
        isPinned: false,
        attachments: [],
        card: null,
      },
      {
        id: 'msg_8_2',
        conversationId: 'conv_8',
        senderId: 'user_4',
        content: '市场活动方案已提交审批',
        contentType: 'text',
        timestamp: ts(1, 1),
        isEdited: false,
        reactions: [],
        threadId: null,
        threadCount: 0,
        threadLastReply: null,
        replyTo: null,
        mentions: [],
        isRead: true,
        isPinned: false,
        attachments: [],
        card: null,
      },
    ],

    conv_9: [
      {
        id: 'msg_9_1',
        conversationId: 'conv_9',
        senderId: 'user_7',
        content: '张明，本周的工作进展如何？遇到什么困难吗？',
        contentType: 'text',
        timestamp: ts(0, 8),
        isEdited: false,
        reactions: [],
        threadId: null,
        threadCount: 0,
        threadLastReply: null,
        replyTo: null,
        mentions: [],
        isRead: true,
        isPinned: false,
        attachments: [],
        card: null,
      },
      {
        id: 'msg_9_2',
        conversationId: 'conv_9',
        senderId: 'user_1',
        content: '总体顺利，需求文档写得差不多了，这周可以完成',
        contentType: 'text',
        timestamp: ts(0, 7),
        isEdited: false,
        reactions: [],
        threadId: null,
        threadCount: 0,
        threadLastReply: null,
        replyTo: null,
        mentions: [],
        isRead: true,
        isPinned: false,
        attachments: [],
        card: null,
      },
      {
        id: 'msg_9_3',
        conversationId: 'conv_9',
        senderId: 'user_7',
        content: '明天1:1会议，我们聊聊Q2规划',
        contentType: 'text',
        timestamp: ts(0, 6),
        isEdited: false,
        reactions: [],
        threadId: null,
        threadCount: 0,
        threadLastReply: null,
        replyTo: null,
        mentions: [],
        isRead: true,
        isPinned: false,
        attachments: [],
        card: null,
      },
    ],

    conv_10: [
      {
        id: 'msg_10_1',
        conversationId: 'conv_10',
        senderId: 'user_8',
        content: '设计规范文档我已经更新了，新增了组件库说明章节',
        contentType: 'text',
        timestamp: ts(2),
        isEdited: false,
        reactions: [],
        threadId: null,
        threadCount: 0,
        threadLastReply: null,
        replyTo: null,
        mentions: [],
        isRead: true,
        isPinned: false,
        attachments: [],
        card: null,
      },
    ],

    conv_bot1: [
      {
        id: 'msg_bot1_1',
        conversationId: 'conv_bot1',
        senderId: 'bot_feishu',
        content: '',
        contentType: 'card',
        timestamp: ts(0, 8),
        isEdited: false,
        reactions: [],
        threadId: null,
        threadCount: 0,
        threadLastReply: null,
        replyTo: null,
        mentions: [],
        isRead: false,
        isPinned: false,
        attachments: [],
        card: {
          title: '📅 会议邀请',
          body: '周思远 邀请您参加"Q2 Kickoff 会议"\n时间：今天 9:00-10:00\n地点：会议室B201',
          color: '#3370FF',
          actions: [{ label: '接受', type: 'accept' }, { label: '拒绝', type: 'decline' }],
        },
      },
      {
        id: 'msg_bot1_2',
        conversationId: 'conv_bot1',
        senderId: 'bot_feishu',
        content: '您有一个新的日历邀请待处理',
        contentType: 'text',
        timestamp: ts(0, 7),
        isEdited: false,
        reactions: [],
        threadId: null,
        threadCount: 0,
        threadLastReply: null,
        replyTo: null,
        mentions: [],
        isRead: true,
        isPinned: false,
        attachments: [],
        card: null,
      },
      {
        id: 'msg_bot1_3',
        conversationId: 'conv_bot1',
        senderId: 'bot_feishu',
        content: '',
        contentType: 'card',
        timestamp: ts(0, 6),
        isEdited: false,
        reactions: [],
        threadId: null,
        threadCount: 0,
        threadLastReply: null,
        replyTo: null,
        mentions: [],
        isRead: true,
        isPinned: false,
        attachments: [],
        card: {
          title: '📋 任务提醒',
          body: '您有 3 个待办任务即将到期\n· 完成Q2产品规划文档 — 今天 18:00\n· Review UI设计稿 — 明天 10:00\n· 提交周报 — 本周五',
          color: '#FF7D00',
          actions: [{ label: '查看任务', type: 'accept' }],
        },
      },
    ],

    conv_bot2: [
      {
        id: 'msg_bot2_1',
        conversationId: 'conv_bot2',
        senderId: 'bot_approval',
        content: '',
        contentType: 'card',
        timestamp: ts(0, 12),
        isEdited: false,
        reactions: [],
        threadId: null,
        threadCount: 0,
        threadLastReply: null,
        replyTo: null,
        mentions: [],
        isRead: true,
        isPinned: false,
        attachments: [],
        card: {
          title: '✅ 审批通过',
          body: '您的年假申请已审批通过\n假期：4月15日 - 4月16日\n审批人：陈丽',
          color: '#34C724',
          actions: [],
        },
      },
      {
        id: 'msg_bot2_2',
        conversationId: 'conv_bot2',
        senderId: 'bot_approval',
        content: '您有一条待审批申请',
        contentType: 'text',
        timestamp: ts(0, 11),
        isEdited: false,
        reactions: [],
        threadId: null,
        threadCount: 0,
        threadLastReply: null,
        replyTo: null,
        mentions: [],
        isRead: true,
        isPinned: false,
        attachments: [],
        card: null,
      },
    ],
  };

  // ─── SPACES ───
  const spaces = [
    { id: 'space_1', name: '我的空间', type: 'personal', ownerId: 'user_1', documents: ['doc_1', 'doc_2', 'doc_8', 'doc_9'], icon: '📁' },
    { id: 'space_2', name: '共享空间', type: 'shared', ownerId: null, documents: ['doc_3', 'doc_4', 'doc_5', 'doc_10'], icon: '👥' },
    { id: 'space_3', name: '知识库', type: 'wiki', ownerId: null, documents: ['doc_6', 'doc_7'], icon: '📚' },
  ];

  // ─── DOCUMENTS ───
  const documents = [
    {
      id: 'doc_1',
      title: 'Q2 产品规划方案',
      type: 'doc',
      icon: '📄',
      ownerId: 'user_1',
      collaborators: ['user_2', 'user_7', 'user_3'],
      content: '# Q2 产品规划方案\n\n## 1. 目标概述\n\n本季度的核心目标是提升用户留存率和扩大活跃用户规模。\n\n## 2. 产品功能规划\n\n### 2.1 新功能开发\n- 智能推荐系统优化\n- 用户反馈机制改进\n- 性能优化和体验提升\n\n## 3. 时间安排\n\n| 阶段 | 时间 | 目标 |\n|------|------|------|\n| 需求确认 | 4月 | 完成PRD |\n| 开发 | 5月 | 完成开发 |\n| 测试上线 | 6月 | 发版 |',
      spaceId: 'space_1',
      parentId: null,
      isStar: true,
      lastEditedBy: 'user_1',
      lastEditedAt: ts(0, 2),
      createdAt: ts(7),
      viewCount: 42,
      wordCount: 1580,
    },
    {
      id: 'doc_2',
      title: '用户调研报告',
      type: 'doc',
      icon: '📄',
      ownerId: 'user_1',
      collaborators: ['user_4'],
      content: '# 用户调研报告\n\n## 调研背景\n\n为了更好地了解用户需求，我们在3月份进行了一次大规模用户调研。\n\n## 主要发现\n\n1. 用户最关注的功能是消息通知\n2. 60%的用户每天使用超过2小时\n3. 移动端用户占比达到70%\n\n## 结论与建议\n\n基于调研数据，建议优先优化消息推送功能和移动端体验。',
      spaceId: 'space_1',
      parentId: null,
      isStar: false,
      lastEditedBy: 'user_1',
      lastEditedAt: ts(3),
      createdAt: ts(14),
      viewCount: 28,
      wordCount: 920,
    },
    {
      id: 'doc_3',
      title: '项目A需求文档',
      type: 'doc',
      icon: '📄',
      ownerId: 'user_1',
      collaborators: ['user_3', 'user_6', 'user_7'],
      content: '# 项目A需求文档 v2.1\n\n## 概述\n\n项目A是面向企业客户的协作工具，本文档描述核心功能需求。\n\n## 功能模块\n\n### 模块一：用户管理\n- 用户注册与登录\n- 权限管理\n- 组织架构管理\n\n### 模块二：任务管理\n- 任务创建与分配\n- 进度跟踪\n- 评论与协作',
      spaceId: 'space_2',
      parentId: null,
      isStar: true,
      lastEditedBy: 'user_1',
      lastEditedAt: ts(0, 5),
      createdAt: ts(10),
      viewCount: 67,
      wordCount: 2340,
    },
    {
      id: 'doc_4',
      title: 'Q1 数据汇总',
      type: 'sheet',
      icon: '📊',
      ownerId: 'user_4',
      collaborators: ['user_1', 'user_7'],
      content: '# Q1 数据汇总表\n\n| 指标 | 目标 | 实际 | 完成率 |\n|------|------|------|--------|\n| 日活用户 | 10万 | 12万 | 120% |\n| 月活用户 | 30万 | 35万 | 117% |\n| 留存率 | 60% | 65% | 108% |\n| 营收 | 500万 | 480万 | 96% |',
      spaceId: 'space_2',
      parentId: null,
      isStar: false,
      lastEditedBy: 'user_4',
      lastEditedAt: ts(5),
      createdAt: ts(30),
      viewCount: 55,
      wordCount: 340,
    },
    {
      id: 'doc_5',
      title: '团队 OKR 看板',
      type: 'bitable',
      icon: '📋',
      ownerId: 'user_7',
      collaborators: ['user_1', 'user_2', 'user_3', 'user_4'],
      content: '# 团队OKR看板\n\n## Q2 目标\n\nO1: 提升产品用户体验评分至4.5分以上\n- KR1: 完成3个核心功能优化\n- KR2: 用户满意度调研评分 ≥ 4.5\n\nO2: 扩大市场覆盖率\n- KR1: 新增企业客户50家\n- KR2: 合作伙伴数量增加20%',
      spaceId: 'space_2',
      parentId: null,
      isStar: false,
      lastEditedBy: 'user_7',
      lastEditedAt: ts(1),
      createdAt: ts(21),
      viewCount: 89,
      wordCount: 560,
    },
    {
      id: 'doc_6',
      title: '设计规范 v2.0',
      type: 'doc',
      icon: '📄',
      ownerId: 'user_8',
      collaborators: ['user_2', 'user_1'],
      content: '# 设计规范 v2.0\n\n## 颜色规范\n\n### 主色调\n- 品牌蓝：#3370FF\n- 浅蓝背景：#E1EAFF\n\n### 功能色\n- 成功绿：#34C724\n- 警告橙：#FF7D00\n- 错误红：#F54A45\n\n## 字体规范\n\n- 标题：PingFang SC，600，20px\n- 正文：PingFang SC，400，14px\n- 辅助：PingFang SC，400，12px',
      spaceId: 'space_3',
      parentId: null,
      isStar: true,
      lastEditedBy: 'user_8',
      lastEditedAt: ts(2),
      createdAt: ts(45),
      viewCount: 123,
      wordCount: 1200,
    },
    {
      id: 'doc_7',
      title: '新员工手册',
      type: 'doc',
      icon: '📄',
      ownerId: 'user_5',
      collaborators: ['user_7'],
      content: '# 新员工手册\n\n## 欢迎加入字节跳动！\n\n## 公司介绍\n\n字节跳动成立于2012年，是一家以技术为驱动的全球化互联网公司。\n\n## 工作制度\n\n- 工作时间：10:00-19:00，弹性1小时\n- 休假制度：法定假日 + 年假10天\n- 餐补：每天35元\n\n## 常用系统\n\n- 飞书：沟通协作\n- 效率平台：OA审批\n- 代码仓库：内部Git平台',
      spaceId: 'space_3',
      parentId: null,
      isStar: false,
      lastEditedBy: 'user_5',
      lastEditedAt: ts(10),
      createdAt: ts(60),
      viewCount: 312,
      wordCount: 1800,
    },
    {
      id: 'doc_8',
      title: '会议纪要-0409',
      type: 'doc',
      icon: '📄',
      ownerId: 'user_1',
      collaborators: ['user_3', 'user_6'],
      content: '# 会议纪要 — 2024-04-09\n\n**参会人员**：张明、王浩、刘洋\n\n**会议主题**：项目A联调安排\n\n## 讨论内容\n\n1. 接口设计方案已确认，共12个接口\n2. 联调时间定在明天下午2点\n3. 前后端同步文档使用飞书文档\n\n## 待办事项\n\n- [ ] 刘洋：接口文档今天完成\n- [ ] 王浩：前端页面今天完成\n- [ ] 张明：测试用例明天完成',
      spaceId: 'space_1',
      parentId: null,
      isStar: false,
      lastEditedBy: 'user_1',
      lastEditedAt: ts(0, 1),
      createdAt: ts(0, 3),
      viewCount: 8,
      wordCount: 280,
    },
    {
      id: 'doc_9',
      title: '竞品分析表',
      type: 'sheet',
      icon: '📊',
      ownerId: 'user_1',
      collaborators: ['user_4'],
      content: '# 竞品分析表\n\n| 产品 | 用户规模 | 核心功能 | 优势 | 劣势 |\n|------|----------|----------|------|------|\n| 飞书 | 1000万+ | 即时通讯+文档+日历 | 深度集成 | 学习成本高 |\n| 钉钉 | 7亿+ | 即时通讯+OA | 用户基数大 | 功能繁杂 |\n| 企业微信 | 5亿+ | 即时通讯+CRM | 微信生态 | 文档弱 |',
      spaceId: 'space_1',
      parentId: null,
      isStar: false,
      lastEditedBy: 'user_1',
      lastEditedAt: ts(4),
      createdAt: ts(20),
      viewCount: 19,
      wordCount: 450,
    },
    {
      id: 'doc_10',
      title: '产品路线图',
      type: 'doc',
      icon: '📄',
      ownerId: 'user_7',
      collaborators: ['user_1', 'user_2', 'user_3'],
      content: '# 产品路线图 2024\n\n## Q1（已完成）\n- ✅ 用户体验优化\n- ✅ 性能提升项目\n- ✅ 新用户引导流程\n\n## Q2（进行中）\n- 🔄 智能推荐系统\n- 🔄 协作功能增强\n- ⏳ 国际化支持\n\n## Q3（规划中）\n- 📋 AI 功能接入\n- 📋 移动端优化\n\n## Q4（规划中）\n- 📋 新平台支持',
      spaceId: 'space_2',
      parentId: null,
      isStar: true,
      lastEditedBy: 'user_7',
      lastEditedAt: ts(1, 3),
      createdAt: ts(15),
      viewCount: 76,
      wordCount: 680,
    },
  ];

  // ─── CALENDARS ───
  const calendars = [
    { id: 'cal_1', name: '我的日历', color: '#3370FF', isDefault: true, isVisible: true, ownerId: 'user_1' },
    { id: 'cal_2', name: '团队日历', color: '#34C724', isDefault: false, isVisible: true, ownerId: 'user_1' },
    { id: 'cal_3', name: '中国节假日', color: '#FF7D00', isDefault: false, isVisible: true, ownerId: null },
  ];

  // ─── EVENTS (this week) ───
  // Week: Mon=weekStart, Tue=+1d, Wed=+2d, Thu=+3d, Fri=+4d
  const events = [
    {
      id: 'event_1',
      title: '周会',
      description: '每周例会，同步工作进展',
      startTime: weekStart + 10 * HOUR,
      endTime: weekStart + 11 * HOUR,
      isAllDay: false,
      location: '会议室B201',
      meetingLink: '',
      organizerId: 'user_7',
      attendees: [
        { userId: 'user_1', status: 'accepted' },
        { userId: 'user_2', status: 'accepted' },
        { userId: 'user_3', status: 'accepted' },
        { userId: 'user_4', status: 'accepted' },
      ],
      color: '#3370FF',
      reminder: 15,
      isRecurring: true,
      calendarId: 'cal_2',
    },
    {
      id: 'event_2',
      title: '技术方案讨论',
      description: '讨论项目A的技术架构方案',
      startTime: weekStart + DAY + 15 * HOUR,
      endTime: weekStart + DAY + 16 * HOUR,
      isAllDay: false,
      location: '会议室A301',
      meetingLink: '',
      organizerId: 'user_6',
      attendees: [
        { userId: 'user_1', status: 'accepted' },
        { userId: 'user_3', status: 'accepted' },
        { userId: 'user_6', status: 'accepted' },
      ],
      color: '#34C724',
      reminder: 15,
      isRecurring: false,
      calendarId: 'cal_2',
    },
    {
      id: 'event_3',
      title: 'Q2 Kickoff',
      description: 'Q2季度启动会',
      startTime: weekStart + 2 * DAY + 9 * HOUR,
      endTime: weekStart + 2 * DAY + 10 * HOUR,
      isAllDay: false,
      location: '大会议室',
      meetingLink: 'https://meeting.feishu.cn/xxx',
      organizerId: 'user_7',
      attendees: [
        { userId: 'user_1', status: 'accepted' },
        { userId: 'user_2', status: 'accepted' },
        { userId: 'user_3', status: 'pending' },
        { userId: 'user_4', status: 'accepted' },
        { userId: 'user_5', status: 'accepted' },
      ],
      color: '#FF7D00',
      reminder: 30,
      isRecurring: false,
      calendarId: 'cal_2',
    },
    {
      id: 'event_4',
      title: '产品评审会议',
      description: '讨论Q2产品方案细节',
      startTime: weekStart + 2 * DAY + 14 * HOUR,
      endTime: weekStart + 2 * DAY + 15 * HOUR,
      isAllDay: false,
      location: '会议室A301',
      meetingLink: '',
      organizerId: 'user_1',
      attendees: [
        { userId: 'user_1', status: 'accepted' },
        { userId: 'user_2', status: 'accepted' },
        { userId: 'user_7', status: 'accepted' },
        { userId: 'user_3', status: 'pending' },
        { userId: 'user_8', status: 'accepted' },
      ],
      color: '#3370FF',
      reminder: 15,
      isRecurring: false,
      calendarId: 'cal_1',
    },
    {
      id: 'event_5',
      title: '1:1 with 周思远',
      description: '季度绩效沟通和职业发展规划',
      startTime: weekStart + 3 * DAY + 16 * HOUR,
      endTime: weekStart + 3 * DAY + 16 * HOUR + 30 * 60000,
      isAllDay: false,
      location: '会议室C101',
      meetingLink: '',
      organizerId: 'user_7',
      attendees: [
        { userId: 'user_1', status: 'accepted' },
        { userId: 'user_7', status: 'accepted' },
      ],
      color: '#9254DE',
      reminder: 5,
      isRecurring: true,
      calendarId: 'cal_1',
    },
    {
      id: 'event_6',
      title: '设计评审',
      description: '评审新版本UI设计稿',
      startTime: weekStart + 3 * DAY + 14 * HOUR,
      endTime: weekStart + 3 * DAY + 15 * HOUR,
      isAllDay: false,
      location: '设计部工区',
      meetingLink: '',
      organizerId: 'user_8',
      attendees: [
        { userId: 'user_1', status: 'accepted' },
        { userId: 'user_2', status: 'accepted' },
        { userId: 'user_8', status: 'accepted' },
      ],
      color: '#EB2F96',
      reminder: 15,
      isRecurring: false,
      calendarId: 'cal_2',
    },
    {
      id: 'event_7',
      title: '团建活动',
      description: '公司团建，下午3点餐厅集合',
      startTime: weekStart + 4 * DAY,
      endTime: weekStart + 4 * DAY + 23 * HOUR + 59 * 60000,
      isAllDay: true,
      location: '公司楼下餐厅',
      meetingLink: '',
      organizerId: 'user_5',
      attendees: [
        { userId: 'user_1', status: 'accepted' },
        { userId: 'user_2', status: 'accepted' },
        { userId: 'user_3', status: 'accepted' },
        { userId: 'user_4', status: 'accepted' },
        { userId: 'user_5', status: 'accepted' },
      ],
      color: '#34C724',
      reminder: 60,
      isRecurring: false,
      calendarId: 'cal_2',
    },
    {
      id: 'event_8',
      title: '午餐',
      description: '',
      startTime: weekStart + 12 * HOUR,
      endTime: weekStart + 13 * HOUR,
      isAllDay: false,
      location: '公司食堂',
      meetingLink: '',
      organizerId: 'user_1',
      attendees: [{ userId: 'user_1', status: 'accepted' }],
      color: '#FA8C16',
      reminder: 5,
      isRecurring: true,
      calendarId: 'cal_1',
    },
    {
      id: 'event_9',
      title: '前端技术分享会',
      description: '王浩分享React性能优化最佳实践',
      startTime: weekStart + DAY + 10 * HOUR,
      endTime: weekStart + DAY + 11 * HOUR,
      isAllDay: false,
      location: '分享区S201',
      meetingLink: 'https://meeting.feishu.cn/tech-share',
      organizerId: 'user_3',
      attendees: [
        { userId: 'user_1', status: 'accepted' },
        { userId: 'user_3', status: 'accepted' },
        { userId: 'user_6', status: 'accepted' },
        { userId: 'user_9', status: 'accepted' },
        { userId: 'user_13', status: 'pending' },
      ],
      color: '#13C2C2',
      reminder: 15,
      isRecurring: false,
      calendarId: 'cal_2',
    },
    {
      id: 'event_10',
      title: '客户回访会议',
      description: '与A公司客户进行季度回访',
      startTime: weekStart + 2 * DAY + 11 * HOUR,
      endTime: weekStart + 2 * DAY + 12 * HOUR,
      isAllDay: false,
      location: '线上会议',
      meetingLink: 'https://meeting.feishu.cn/client-a',
      organizerId: 'user_4',
      attendees: [
        { userId: 'user_1', status: 'accepted' },
        { userId: 'user_4', status: 'accepted' },
        { userId: 'user_11', status: 'accepted' },
      ],
      color: '#F54A45',
      reminder: 30,
      isRecurring: false,
      calendarId: 'cal_1',
    },
    {
      id: 'event_11',
      title: '新人培训',
      description: '新员工入职培训和系统使用介绍',
      startTime: weekStart + 4 * DAY + 9 * HOUR,
      endTime: weekStart + 4 * DAY + 11 * HOUR,
      isAllDay: false,
      location: '培训室T301',
      meetingLink: '',
      organizerId: 'user_5',
      attendees: [
        { userId: 'user_5', status: 'accepted' },
        { userId: 'user_12', status: 'accepted' },
      ],
      color: '#722ED1',
      reminder: 60,
      isRecurring: false,
      calendarId: 'cal_2',
    },
  ];

  // ─── MEETINGS ───
  const meetings = [
    {
      id: 'meeting_1',
      title: 'Q2 Kickoff 全员大会',
      status: 'upcoming',
      startTime: weekStart + 2 * DAY + 9 * HOUR,
      endTime: weekStart + 2 * DAY + 10 * HOUR,
      organizerId: 'user_7',
      attendees: ['user_1', 'user_2', 'user_3', 'user_4', 'user_5', 'user_6', 'user_7', 'user_8'],
      meetingLink: 'https://meeting.feishu.cn/q2-kickoff',
      meetingNo: '689-342-118',
      hasRecording: false,
      isRecurring: false,
    },
    {
      id: 'meeting_2',
      title: '产品评审会议',
      status: 'upcoming',
      startTime: weekStart + 2 * DAY + 14 * HOUR,
      endTime: weekStart + 2 * DAY + 15 * HOUR,
      organizerId: 'user_1',
      attendees: ['user_1', 'user_2', 'user_7', 'user_3', 'user_8'],
      meetingLink: 'https://meeting.feishu.cn/product-review',
      meetingNo: '521-876-443',
      hasRecording: false,
      isRecurring: false,
    },
    {
      id: 'meeting_3',
      title: '每周站会',
      status: 'upcoming',
      startTime: weekStart + 10 * HOUR,
      endTime: weekStart + 10 * HOUR + 30 * 60000,
      organizerId: 'user_7',
      attendees: ['user_1', 'user_2', 'user_3', 'user_6', 'user_9'],
      meetingLink: 'https://meeting.feishu.cn/standup',
      meetingNo: '334-221-556',
      hasRecording: false,
      isRecurring: true,
    },
    {
      id: 'meeting_4',
      title: '技术方案评审',
      status: 'ended',
      startTime: ts(1, 15),
      endTime: ts(1, 14),
      organizerId: 'user_6',
      attendees: ['user_1', 'user_3', 'user_6', 'user_13'],
      meetingLink: 'https://meeting.feishu.cn/tech-review',
      meetingNo: '887-112-334',
      hasRecording: true,
      isRecurring: false,
    },
    {
      id: 'meeting_5',
      title: '项目A需求对齐',
      status: 'ended',
      startTime: ts(2, 10),
      endTime: ts(2, 9),
      organizerId: 'user_1',
      attendees: ['user_1', 'user_3', 'user_6', 'user_7'],
      meetingLink: 'https://meeting.feishu.cn/project-a',
      meetingNo: '223-445-667',
      hasRecording: true,
      isRecurring: false,
    },
    {
      id: 'meeting_6',
      title: '设计评审会',
      status: 'ended',
      startTime: ts(3, 14),
      endTime: ts(3, 13),
      organizerId: 'user_8',
      attendees: ['user_1', 'user_2', 'user_8', 'user_10'],
      meetingLink: 'https://meeting.feishu.cn/design-review',
      meetingNo: '445-667-889',
      hasRecording: false,
      isRecurring: false,
    },
  ];
  const todayEnd = new Date();
  todayEnd.setHours(23, 59, 59, 999);
  const tasks = [
    {
      id: 'task_1',
      title: '完成产品需求文档',
      description: '需要在周五前完成PRD初稿，包括用户故事和验收标准',
      status: 'in_progress',
      priority: 'high',
      assigneeId: 'user_1',
      creatorId: 'user_7',
      dueDate: weekStart + 4 * DAY + 18 * HOUR,
      tags: ['产品', 'Q2'],
      relatedDocId: 'doc_3',
      relatedConvId: 'conv_1',
      createdAt: ts(3),
      completedAt: null,
    },
    {
      id: 'task_2',
      title: '评审设计稿',
      description: '评审项目A的UI设计稿，给出修改意见',
      status: 'todo',
      priority: 'medium',
      assigneeId: 'user_1',
      creatorId: 'user_2',
      dueDate: weekStart + 2 * DAY + 18 * HOUR,
      tags: ['设计', '评审'],
      relatedDocId: 'doc_6',
      relatedConvId: null,
      createdAt: ts(2),
      completedAt: null,
    },
    {
      id: 'task_3',
      title: '更新项目A排期',
      description: '根据最新需求更新项目A的开发排期文档',
      status: 'todo',
      priority: 'high',
      assigneeId: 'user_1',
      creatorId: 'user_1',
      dueDate: weekStart + 3 * DAY + 18 * HOUR,
      tags: ['项目管理'],
      relatedDocId: null,
      relatedConvId: 'conv_5',
      createdAt: ts(1),
      completedAt: null,
    },
    {
      id: 'task_4',
      title: '整理Q1数据报告',
      description: 'Q1数据报告汇总，已完成',
      status: 'done',
      priority: 'low',
      assigneeId: 'user_1',
      creatorId: 'user_7',
      dueDate: ts(-3),
      tags: ['数据', 'Q1'],
      relatedDocId: 'doc_4',
      relatedConvId: null,
      createdAt: ts(10),
      completedAt: ts(2),
    },
    {
      id: 'task_5',
      title: '准备周会材料',
      description: '整理本周工作进展和下周计划',
      status: 'todo',
      priority: 'medium',
      assigneeId: 'user_1',
      creatorId: 'user_1',
      dueDate: weekStart + 10 * HOUR,
      tags: ['会议'],
      relatedDocId: null,
      relatedConvId: null,
      createdAt: ts(0, 12),
      completedAt: null,
    },
    {
      id: 'task_6',
      title: '回复客户反馈',
      description: '回复企业客户关于数据导出功能的反馈邮件',
      status: 'in_progress',
      priority: 'high',
      assigneeId: 'user_1',
      creatorId: 'user_4',
      dueDate: todayEnd.getTime(),
      tags: ['客户', '紧急'],
      relatedDocId: null,
      relatedConvId: null,
      createdAt: ts(0, 8),
      completedAt: null,
    },
  ];

  // ─── APPROVALS ───
  const approvals = [
    {
      id: 'approval_1',
      type: 'leave',
      title: '年假申请 - 张明',
      status: 'pending',
      applicantId: 'user_1',
      approverId: 'user_7',
      details: {
        leaveType: '年假',
        startDate: '2024-04-15',
        endDate: '2024-04-16',
        days: 2,
        reason: '个人事务处理',
      },
      createdAt: ts(1),
      updatedAt: null,
      comment: '',
    },
    {
      id: 'approval_4',
      type: 'leave',
      title: '病假申请 - 周思远',
      status: 'pending',
      applicantId: 'user_7',
      approverId: 'user_1',
      details: {
        leaveType: '病假',
        startDate: '2024-04-12',
        endDate: '2024-04-12',
        days: 1,
        reason: '身体不适，需要休息就医',
      },
      createdAt: ts(0, 3),
      updatedAt: null,
      comment: '',
    },
    {
      id: 'approval_2',
      type: 'expense',
      title: '差旅报销 - 赵艺',
      status: 'approved',
      applicantId: 'user_4',
      approverId: 'user_7',
      details: {
        amount: 1580,
        currency: 'CNY',
        purpose: '出差上海参加行业峰会',
        date: '2024-04-05',
        items: ['机票：880元', '酒店：500元', '餐饮：200元'],
      },
      createdAt: ts(5),
      updatedAt: ts(3),
      comment: '审批通过，请财务核实后报销',
    },
    {
      id: 'approval_3',
      type: 'travel',
      title: '出差申请 - 王浩',
      status: 'rejected',
      applicantId: 'user_3',
      approverId: 'user_6',
      details: {
        destination: '深圳',
        startDate: '2024-04-18',
        endDate: '2024-04-19',
        purpose: '拜访客户现场调研',
        estimatedCost: 2000,
      },
      createdAt: ts(4),
      updatedAt: ts(2),
      comment: '当前项目冲刺阶段，不宜出差，请延期申请',
    },
  ];

  return {
    currentUser: users[0],
    users,
    conversations,
    messages,
    documents,
    spaces,
    calendars,
    events,
    meetings,
    departments,
    tasks,
    approvals,
    // UI state
    activeConversationId: 'conv_1',
    activeModule: 'messenger',
    searchQuery: '',
    threadPanelMessageId: null,
    sidebarCollapsed: false,
    favorites: [],
    activeContactId: null,
    settings: {
      language: 'zh-CN',
      theme: 'light',
      fontSize: 'medium',
      autoStart: false,
      doNotDisturb: 'off',
      messagePermission: 'everyone',
      notificationSound: true,
      desktopNotification: true,
      mentionNotification: true,
      emailDigest: false,
      showOnlineStatus: true,
      readReceipt: true,
      allowSearch: true,
    },
  };
}
